#!/usr/bin/env python3
"""T24 independent reload repeatability audit: exactly one eval forward, no training.
Reference .pt files are comparison oracles only, never resume inputs.
All CUDA requires a Slurm allocation. No source patch or future PLY reset.
"""
import argparse, copy, hashlib, json, logging, os, subprocess, sys, time, traceback, types
from pathlib import Path
import numpy as np

def sha(p):
    return hashlib.sha256(Path(p).read_bytes()).hexdigest()

def main():
    ap=argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--workspace',type=Path,required=True)
    ap.add_argument('--output',type=Path,required=True)
    ap.add_argument('--label',choices=['A','B'],required=True)
    ap.add_argument('--checkpoint-dir',type=Path,required=True)
    args=ap.parse_args()
    assert os.environ.get('SLURM_JOB_ID'), 'CUDA requires Slurm'
    root=args.workspace.resolve(); repo=root/'SoMA'; os.chdir(repo); sys.path.insert(0,str(repo))
    cp=repo/'docs/deform360/contracts/008-pink-cloth/episode_0'
    args.output.mkdir(parents=True,exist_ok=True)
    report_path=args.output/(args.label+'_report.json')
    assert not report_path.exists(), 'No overwrite'
    report={'process':args.label,'status':'IN_PROGRESS','job_id':os.environ['SLURM_JOB_ID'],
            'pid':os.getpid(),'tool_sha256':sha(__file__), 'seed':5,
            'scope':'T24 A/B independent reload; zero training, one eval/no_grad forward',
            'targets':[123], 'head':subprocess.check_output(['git','rev-parse','HEAD'],text=True).strip()}
    started=time.monotonic()
    try:
        execute(args,root,repo,cp,report)
        report['status']='PASS'
    except Exception:
        report['status']='FAIL';report['exception']=traceback.format_exc()
        raise
    finally:
        report['wall_seconds']=time.monotonic()-started
        report_path.write_text(json.dumps(report,indent=2)+'\n')
        print('T24 AB',args.label,report['status'],flush=True)

def execute(args,root,repo,cp,report):
    import torch
    from mmcv import Config
    from mmcv.runner import build_runner, build_optimizer
    from mmgs.datasets.embodied_dataset import EmbodiedDataset
    from mmgs.models.builder import build_simulator
    import mmgs.core.runner
    assert torch.cuda.is_available()
    report['gpu']=subprocess.check_output(['nvidia-smi','--query-gpu=name,memory.total','--format=csv,noheader'],text=True).strip()
    torch.manual_seed(5);np.random.seed(5);torch.set_num_threads(4)
    torch.backends.cudnn.benchmark=False
    torch.backends.cudnn.deterministic=True
    source_files=['mmgs/models/simulators/gs_simulator_embodied.py','mmgs/models/utils/dgl_graph.py',
        'mmgs/models/heads/acc_decoder.py','mmgs/datasets/embodied_dataset.py']
    report['source_sha256']={p:sha(repo/p) for p in source_files}
    sample_report=json.loads((cp/'dataset_sample_contract.json').read_text())
    env=sample_report['configurations']['A']['env_cfg']
    scene=Path(env['data_dir'])/env['scene_list'][0];name=scene.name
    immutable={str(p):sha(p) for p in scene.rglob('*') if p.is_file() and 'cluster_mask' not in p.parts and 'controller_mask' not in p.parts}
    # Directory links are not traversed by rglob: explicitly hash supervised images.
    for i in range(2):
        for frame in range(0,155,10):
            for p in [scene/'color'/str(i)/f'{frame}.png',scene/'mask'/str(i)/'1'/f'{frame}.png']:
                immutable[str(p)]=sha(p)
    np.random.seed(5);dataset=EmbodiedDataset(env_cfg=env,phase='train');sample=dataset[0]
    assert dataset.idx_mapping[0][2]==[0,1]
    assert sample['inputs']['gs_aligned_frame']==0 and sample['meta']['seq_num'].item()==10
    assert env['split_list'][name]==[[0,155]] and env['frame_gap']==10
    def batch(x):
        if isinstance(x,np.ndarray):return torch.from_numpy(x).unsqueeze(0).cuda()
        if isinstance(x,torch.Tensor):return x.unsqueeze(0).cuda()
        if isinstance(x,dict):return {k:batch(v) for k,v in x.items()}
        if isinstance(x,list):return [batch(v) for v in x]
        return x
    data=batch(sample);inputs=data['inputs'];gt=data['gt_label'];meta=data['meta']
    for cam in inputs['cam']:cam.to_device('cuda')
    # Official stage1 configuration previously generated by path-only relocation.
    cfgpath=root/'environment/soma-stage1-20260923/cloth_lift_stage1_external_data.py'
    cfg=Config.fromfile(str(cfgpath));mc=copy.deepcopy(cfg.model)
    mc['gs_scene']=[dict(name=name,model_path=str(scene/'pi3/gs/point_cloud/iteration_10000/point_cloud.ply'),sh_degree=0,num_seq=1,attr_name='rope')]
    mc['cluster_cfg']=env['cluster_cfg'];mc['controller_cfg']=env['controller_cfg']
    mc['train_cfg'].update(step_initial=1,max_rollout_step=1)
    report['model_config']=dict(mc);report['dataset_env_cfg']=env
    report['config_provenance']={'path':str(cfgpath),'sha256':sha(cfgpath),'basis':'Official cloth_lift stage1 with sample data paths relocated; scene/cluster/controller and rollout only overridden for this check.'}
    model=build_simulator(mc).cuda();model.init_weights();model.train()
    gaussian=model.gs_scene_dict[name];N=len(gaussian.get_xyz);assert N==12861
    gaussian_fields=['_xyz','_features_dc','_features_rest','_opacity','_scaling','_rotation']
    gaussian_before={k:getattr(gaussian,k).detach().clone() for k in gaussian_fields}
    registered={id(p) for p in model.parameters()}
    assert not any(id(getattr(gaussian,k)) in registered for k in gaussian_fields)
    traj=inputs['controller_trajectory'][0].float();assert tuple(traj.shape)==(16,30,3)
    expected=np.load(root/json.loads((cp/'controller_trajectory_contract.json').read_text())['output']['path_relative_to_workspace'],allow_pickle=False)[0:155:10]
    assert torch.equal(traj.cpu(),torch.from_numpy(expected))
    mapping=[[x[0].squeeze(0).long(),x[1].squeeze(0).long()] for x in inputs['p2c_mapping']]
    grouping=json.loads((cp/'controller_grouping_contract.json').read_text())
    for i,v in enumerate(grouping['p2c']):assert mapping[i][0].cpu().tolist()==v

    def cpu(x):
        if torch.is_tensor(x):return x.detach().cpu().clone()
        if isinstance(x,dict):return {k:cpu(v) for k,v in x.items()}
        if isinstance(x,list):return [cpu(v) for v in x]
        if isinstance(x,tuple):return tuple(cpu(v) for v in x)
        return copy.deepcopy(x)
    def exact(a,b,path='state'):
        if torch.is_tensor(a):
            assert torch.is_tensor(b) and a.shape==b.shape and a.dtype==b.dtype,path
            assert torch.isfinite(a).all() and torch.isfinite(b).all(),path
            assert torch.equal(a.cpu(),b.cpu()),path
        elif isinstance(a,dict):
            assert a.keys()==b.keys(),path+' keys'
            for k in a:exact(a[k],b[k],path+'/'+str(k))
        elif isinstance(a,(list,tuple)):
            assert type(a)==type(b) and len(a)==len(b),path
            for i,(x,y) in enumerate(zip(a,b)):exact(x,y,path+'/'+str(i))
        else:assert a==b,(path,a,b)
    def finite(x,path='value'):
        if torch.is_tensor(x):assert torch.isfinite(x).all(),path+' nonfinite'
        elif isinstance(x,dict):
            for k,v in x.items():finite(v,path+'/'+str(k))
        elif isinstance(x,(list,tuple)):
            for i,v in enumerate(x):finite(v,path+'/'+str(i))
    # Match T22 optimizer membership, including exclusion of nontrainable normalizer stats.
    optcfg=dict(cfg.optimizer);assert optcfg.pop('type')=='Adam'
    named={n:p for n,p in model.named_parameters() if p.requires_grad}
    optimizer=torch.optim.Adam(list(named.values()),**optcfg)
    report['optimizer_parameter_names']=list(named)
    assert not any(id(getattr(gaussian,k)) in {id(p) for g in optimizer.param_groups for p in g['params']} for k in gaussian_fields)
    def one_step():
        # Same real preprocessing/encode/decode/loss calls as T21/T22. No surrogate model.
        xyz=gaussian.get_xyz;cov=gaussian.get_covariance()
        attr=model.scene_attr[model._scene_attr_dict[name]].expand(N,-1)
        volume=torch.prod(gaussian.get_scaling*inputs['volume_scalar'].squeeze(0),dim=-1,keepdim=True)
        pin=torch.zeros((N+30,1),device='cuda');pin[:30]=1
        graphs,connections=model._preprocess(xyz.detach(),xyz,xyz,traj[0].detach(),traj[1].detach(),traj[0],
            attr,volume,cov,inputs['external'].squeeze(0),mapping,pin_mask=pin)
        labels=[v[0,1] for v in gt]
        out=model.encode_decode(graphs,connections,gaussian,inputs['cam'],
            cov.detach().clone(),xyz.detach().clone(),30,register_norm=True,
            gt_label=labels,rollout_size=1,cln_gaussian=gaussian,white_bg_list=inputs.get('white_bg'))
        finite(out,'encode_decode')
        losses=out[-1]
        losses.update(model._encode_decode_train(out[4],labels,
            [m[0,1] for m in inputs['controller_img_mask_list']],inputs['bbox'][0,:,1]))
        finite(losses,'loss')
        return losses,{'pred_pos':out[0],'pred_cov':out[1],'render':out[4]}
    runner=build_runner(dict(type='EpochRunner',max_epochs=1),default_args=dict(
        model=model,optimizer=optimizer,work_dir=str(args.output),logger=logging.getLogger('t24'),
        meta={'t24':'new finite rollout1 state','seed':5,'source_targets':[123]}))
    report['absent_runtime_attributes']=[k for k in ['global_step','iters_per_epoch'] if not hasattr(model,k)]
    checkpoint=args.checkpoint_dir/'epoch_1.pth'
    refpath=args.checkpoint_dir/'reference_state.pt'
    checkpoint_hash_before=sha(checkpoint)
    def runtime():
        return {k:getattr(model,k) for k in ['num_iter','num_epoch','global_step','iters_per_epoch','is_est_vel'] if hasattr(model,k)}
    def fixed_output():
        model.eval()
        before=cpu(model.state_dict());optbefore=cpu(optimizer.state_dict());rtbefore=runtime()
        with torch.no_grad():loss,output=one_step()
        exact(before,cpu(model.state_dict()),'eval_state_unchanged')
        exact(optbefore,cpu(optimizer.state_dict()),'eval_optimizer_unchanged')
        exact(rtbefore,runtime(),'eval_runtime_unchanged')
        finite([loss,output],'fixed_output')
        return cpu({'steps':[output],'loss':loss})
    reference=torch.load(refpath,map_location='cpu',weights_only=False)
    exact(reference['optimizer_parameter_names'],list(named),'optimizer_name_order')
    runner.resume(str(checkpoint),map_location='cpu')
    exact(reference['model'],cpu(model.state_dict()),'resumed_model')
    exact(reference['optimizer'],cpu(optimizer.state_dict()),'resumed_optimizer')
    exact(reference['counters'],{'epoch':runner.epoch,'iter':runner.iter},'resumed_counters')
    exact(reference['immutable'],immutable,'input_file_hashes')
    def digest(value):
        h=hashlib.sha256()
        def feed(x):
            if torch.is_tensor(x):
                x=x.detach().cpu().contiguous()
                h.update(str(x.dtype).encode());h.update(str(tuple(x.shape)).encode());h.update(x.numpy().tobytes())
            elif isinstance(x,np.ndarray):
                h.update(str(x.dtype).encode());h.update(str(x.shape).encode());h.update(x.tobytes())
            elif isinstance(x,dict):
                for k in sorted(x,key=str):h.update(str(k).encode());feed(x[k])
            elif isinstance(x,(list,tuple)):
                h.update(str(len(x)).encode())
                for y in x:feed(y)
            elif x is None or isinstance(x,(str,int,float,bool,np.number)):
                h.update(str(x).encode())
            else:
                raise TypeError('Unhandled input hash type '+str(type(x)))
        feed(value);return h.hexdigest()
    camkeys=['R','T','FoVx','FoVy','image_width','image_height','world_view_transform',
             'projection_matrix','full_proj_transform','camera_center','cam_plane_2_img']
    hashdata={**data,'inputs':{**inputs,'cam':[{k:getattr(c,k) for k in camkeys} for c in inputs['cam']]}}
    report.update(checkpoint_sha256=checkpoint_hash_before,
        config_sha256=digest({'model':dict(mc),'env':env,'optimizer':dict(cfg.optimizer)}),
        fixed_input_sha256=digest(hashdata),model_sha256=digest(model.state_dict()),
        optimizer_sha256=digest(optimizer.state_dict()),initial_gaussian_sha256=digest(gaussian_before),
        model_exact=True,optimizer_exact=True,normalizer_exact=True,counters_exact=True,
        counters={'epoch':runner.epoch,'iter':runner.iter},runtime=runtime(),
        backend={'cudnn_benchmark':torch.backends.cudnn.benchmark,'cudnn_deterministic':torch.backends.cudnn.deterministic,
                 'deterministic_algorithms':torch.are_deterministic_algorithms_enabled(),
                 'torch_version':str(torch.__version__),'cuda_version':torch.version.cuda})
    # Only forward call in this process; fixed_output asserts no model/optimizer/runtime mutation.
    output=fixed_output()
    artifact=args.output/(args.label+'_output.pt');assert not artifact.exists()
    torch.save(output,artifact)
    report['output']={'path':str(artifact),'bytes':artifact.stat().st_size,'sha256':sha(artifact)}
    report['forward_count']=1;report['optimizer_steps']=0;report['all_output_finite']=True
    for k,v in gaussian_before.items():exact(v,getattr(gaussian,k).detach(),k)
    for p,h in immutable.items():assert sha(p)==h,p
    for p,h in report['source_sha256'].items():assert sha(repo/p)==h,p
    assert sha(checkpoint)==checkpoint_hash_before
    assert digest(hashdata)==report['fixed_input_sha256']
    report['input_checkpoint_source_unchanged']=True

if __name__=='__main__':main()
