#!/usr/bin/env python3
"""T24: same-process fresh model isolation; guarded rollout1 save, M0/M1 repeats, independent A.
Reference .pt files are comparison oracles only, never resume inputs.
All CUDA requires a Slurm allocation. No source patch or future PLY reset.
"""
import argparse, copy, hashlib, json, logging, os, subprocess, sys, time, traceback, types
from pathlib import Path
import numpy as np

def sha(p):
    return hashlib.sha256(Path(p).read_bytes()).hexdigest()

def main():
    ap=argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--workspace',type=Path,required=True)
    ap.add_argument('--output',type=Path,required=True)
    ap.add_argument('--label',choices=['S','A'],required=True)
    args=ap.parse_args()
    assert os.environ.get('SLURM_JOB_ID'), 'CUDA requires Slurm'
    root=args.workspace.resolve(); repo=root/'SoMA'; os.chdir(repo); sys.path.insert(0,str(repo))
    cp=repo/'docs/deform360/contracts/008-pink-cloth/episode_0'
    args.output.mkdir(parents=True,exist_ok=True)
    report_path=args.output/(args.label+'_report.json')
    assert not report_path.exists(), 'No overwrite'
    report={'process':args.label,'status':'IN_PROGRESS','job_id':os.environ['SLURM_JOB_ID'],
            'pid':os.getpid(),'tool_sha256':sha(__file__), 'seed':5,
            'scope':'T24 M0/M1 same process versus fresh process A; no backend/tolerance changes',
            'targets':[123], 'head':subprocess.check_output(['git','rev-parse','HEAD'],text=True).strip()}
    started=time.monotonic()
    try:
        execute(args,root,repo,cp,report)
        report['status']='PASS'
    except Exception:
        report['status']='FAIL';report['exception']=traceback.format_exc()
        raise
    finally:
        report['wall_seconds']=time.monotonic()-started
        report_path.write_text(json.dumps(report,indent=2)+'\n')
        print('T24 SAB',args.label,report['status'],flush=True)

def execute(args,root,repo,cp,report):
    import torch
    import random
    events=[];report['events']=events
    def event(name,**detail):
        events.append({'index':len(events)+1,'event':name,'seconds':time.monotonic(),**detail})
    event('instantiate_begin')
    from mmcv import Config
    from mmcv.runner import build_runner, build_optimizer
    from mmgs.datasets.embodied_dataset import EmbodiedDataset
    from mmgs.models.builder import build_simulator
    import mmgs.core.runner
    assert torch.cuda.is_available()
    report['gpu']=subprocess.check_output(['nvidia-smi','--query-gpu=name,memory.total','--format=csv,noheader'],text=True).strip()
    torch.manual_seed(5);np.random.seed(5);torch.set_num_threads(4)
    torch.backends.cudnn.benchmark=False
    torch.backends.cudnn.deterministic=True
    source_files=['mmgs/models/simulators/gs_simulator_embodied.py','mmgs/models/utils/dgl_graph.py',
        'mmgs/models/heads/acc_decoder.py','mmgs/datasets/embodied_dataset.py']
    report['source_sha256']={p:sha(repo/p) for p in source_files}
    sample_report=json.loads((cp/'dataset_sample_contract.json').read_text())
    env=sample_report['configurations']['A']['env_cfg']
    scene=Path(env['data_dir'])/env['scene_list'][0];name=scene.name
    immutable={str(p):sha(p) for p in scene.rglob('*') if p.is_file() and 'cluster_mask' not in p.parts and 'controller_mask' not in p.parts}
    # Directory links are not traversed by rglob: explicitly hash supervised images.
    for i in range(2):
        for frame in range(0,155,10):
            for p in [scene/'color'/str(i)/f'{frame}.png',scene/'mask'/str(i)/'1'/f'{frame}.png']:
                immutable[str(p)]=sha(p)
    np.random.seed(5);dataset=EmbodiedDataset(env_cfg=env,phase='train');sample=dataset[0]
    assert dataset.idx_mapping[0][2]==[0,1]
    assert sample['inputs']['gs_aligned_frame']==0 and sample['meta']['seq_num'].item()==10
    assert env['split_list'][name]==[[0,155]] and env['frame_gap']==10
    def batch(x):
        if isinstance(x,np.ndarray):return torch.from_numpy(x).unsqueeze(0).cuda()
        if isinstance(x,torch.Tensor):return x.unsqueeze(0).cuda()
        if isinstance(x,dict):return {k:batch(v) for k,v in x.items()}
        if isinstance(x,list):return [batch(v) for v in x]
        return x
    data=batch(sample);inputs=data['inputs'];gt=data['gt_label'];meta=data['meta']
    for cam in inputs['cam']:cam.to_device('cuda')
    # Official stage1 configuration previously generated by path-only relocation.
    cfgpath=root/'environment/soma-stage1-20260923/cloth_lift_stage1_external_data.py'
    cfg=Config.fromfile(str(cfgpath));mc=copy.deepcopy(cfg.model)
    mc['gs_scene']=[dict(name=name,model_path=str(scene/'pi3/gs/point_cloud/iteration_10000/point_cloud.ply'),sh_degree=0,num_seq=1,attr_name='rope')]
    mc['cluster_cfg']=env['cluster_cfg'];mc['controller_cfg']=env['controller_cfg']
    mc['train_cfg'].update(step_initial=1,max_rollout_step=1)
    report['model_config']=dict(mc);report['dataset_env_cfg']=env
    report['config_provenance']={'path':str(cfgpath),'sha256':sha(cfgpath),'basis':'Official cloth_lift stage1 with sample data paths relocated; scene/cluster/controller and rollout only overridden for this check.'}
    model=build_simulator(mc).cuda();model.init_weights();model.train()
    event('instantiate_complete')
    gaussian=model.gs_scene_dict[name];N=len(gaussian.get_xyz);assert N==12861
    gaussian_fields=['_xyz','_features_dc','_features_rest','_opacity','_scaling','_rotation']
    gaussian_before={k:getattr(gaussian,k).detach().clone() for k in gaussian_fields}
    registered={id(p) for p in model.parameters()}
    assert not any(id(getattr(gaussian,k)) in registered for k in gaussian_fields)
    traj=inputs['controller_trajectory'][0].float();assert tuple(traj.shape)==(16,30,3)
    expected=np.load(root/json.loads((cp/'controller_trajectory_contract.json').read_text())['output']['path_relative_to_workspace'],allow_pickle=False)[0:155:10]
    assert torch.equal(traj.cpu(),torch.from_numpy(expected))
    mapping=[[x[0].squeeze(0).long(),x[1].squeeze(0).long()] for x in inputs['p2c_mapping']]
    grouping=json.loads((cp/'controller_grouping_contract.json').read_text())
    for i,v in enumerate(grouping['p2c']):assert mapping[i][0].cpu().tolist()==v

    def cpu(x):
        if torch.is_tensor(x):return x.detach().cpu().clone()
        if isinstance(x,dict):return {k:cpu(v) for k,v in x.items()}
        if isinstance(x,list):return [cpu(v) for v in x]
        if isinstance(x,tuple):return tuple(cpu(v) for v in x)
        return copy.deepcopy(x)
    def exact(a,b,path='state'):
        if torch.is_tensor(a):
            assert torch.is_tensor(b) and a.shape==b.shape and a.dtype==b.dtype,path
            assert torch.isfinite(a).all() and torch.isfinite(b).all(),path
            assert torch.equal(a.cpu(),b.cpu()),path
        elif isinstance(a,dict):
            assert a.keys()==b.keys(),path+' keys'
            for k in a:exact(a[k],b[k],path+'/'+str(k))
        elif isinstance(a,(list,tuple)):
            assert type(a)==type(b) and len(a)==len(b),path
            for i,(x,y) in enumerate(zip(a,b)):exact(x,y,path+'/'+str(i))
        else:assert a==b,(path,a,b)
    def finite(x,path='value'):
        if torch.is_tensor(x):assert torch.isfinite(x).all(),path+' nonfinite'
        elif isinstance(x,dict):
            for k,v in x.items():finite(v,path+'/'+str(k))
        elif isinstance(x,(list,tuple)):
            for i,v in enumerate(x):finite(v,path+'/'+str(i))
    # Match T22 optimizer membership, including exclusion of nontrainable normalizer stats.
    optcfg=dict(cfg.optimizer);assert optcfg.pop('type')=='Adam'
    named={n:p for n,p in model.named_parameters() if p.requires_grad}
    optimizer=torch.optim.Adam(list(named.values()),**optcfg)
    report['optimizer_parameter_names']=list(named)
    assert not any(id(getattr(gaussian,k)) in {id(p) for g in optimizer.param_groups for p in g['params']} for k in gaussian_fields)
    def one_step():
        # Same real preprocessing/encode/decode/loss calls as T21/T22. No surrogate model.
        xyz=gaussian.get_xyz;cov=gaussian.get_covariance()
        attr=model.scene_attr[model._scene_attr_dict[name]].expand(N,-1)
        volume=torch.prod(gaussian.get_scaling*inputs['volume_scalar'].squeeze(0),dim=-1,keepdim=True)
        pin=torch.zeros((N+30,1),device='cuda');pin[:30]=1
        graphs,connections=model._preprocess(xyz.detach(),xyz,xyz,traj[0].detach(),traj[1].detach(),traj[0],
            attr,volume,cov,inputs['external'].squeeze(0),mapping,pin_mask=pin)
        labels=[v[0,1] for v in gt]
        out=model.encode_decode(graphs,connections,gaussian,inputs['cam'],
            cov.detach().clone(),xyz.detach().clone(),30,register_norm=True,
            gt_label=labels,rollout_size=1,cln_gaussian=gaussian,white_bg_list=inputs.get('white_bg'))
        finite(out,'encode_decode')
        losses=out[-1]
        losses.update(model._encode_decode_train(out[4],labels,
            [m[0,1] for m in inputs['controller_img_mask_list']],inputs['bbox'][0,:,1]))
        finite(losses,'loss')
        return losses,{'pred_pos':out[0],'pred_cov':out[1],'render':out[4]}
    runner=build_runner(dict(type='EpochRunner',max_epochs=1),default_args=dict(
        model=model,optimizer=optimizer,work_dir=str(args.output),logger=logging.getLogger('t24'),
        meta={'t24':'new finite rollout1 state','seed':5,'source_targets':[123]}))
    report['absent_runtime_attributes']=[k for k in ['global_step','iters_per_epoch'] if not hasattr(model,k)]
    event('runner_optimizer_instantiated')
    checkpoint=args.output/'epoch_1.pth'
    refpath=args.output/'reference_state.pt'
    outputpath=args.output/'reference_output.pt'
    def runtime():
        return {k:getattr(model,k) for k in ['num_iter','num_epoch','global_step','iters_per_epoch','is_est_vel'] if hasattr(model,k)}
    def inspect_value(x):
        if torch.is_tensor(x):
            t=x.detach().cpu().contiguous()
            return {'kind':'tensor','shape':list(x.shape),'dtype':str(x.dtype),'device':str(x.device),
                    'stride':list(x.stride()),'storage_offset':x.storage_offset(),'requires_grad':x.requires_grad,
                    'is_leaf':x.is_leaf,'sha256':hashlib.sha256(t.numpy().tobytes()).hexdigest()}
        if isinstance(x,np.ndarray):
            return {'kind':'numpy','shape':list(x.shape),'dtype':str(x.dtype),'sha256':hashlib.sha256(x.tobytes()).hexdigest()}
        if isinstance(x,dict):return {str(k):inspect_value(v) for k,v in x.items()}
        if isinstance(x,(list,tuple)):return [inspect_value(v) for v in x]
        if isinstance(x,(str,int,float,bool)) or x is None:return x
        if isinstance(x,np.number):return x.item()
        return {'type':type(x).__name__}
    def forward_snapshot():
        candidate_names=['scene_init_pos','scene_init_cov','scene_init_prev_pos','scene_initn1_pos','scene_init0_pos']
        plain_modules={}
        for n,m in model.named_modules():
            attrs={k:inspect_value(v) for k,v in vars(m).items()
                   if k not in ['_parameters','_buffers','_modules'] and
                   (torch.is_tensor(v) or isinstance(v,(str,int,float,bool,np.ndarray)) or
                    (isinstance(v,(dict,list,tuple)) and not k.startswith('_')))}
            if attrs:plain_modules[n]=attrs
        camkeys=['R','T','FoVx','FoVy','image_width','image_height','world_view_transform','projection_matrix','full_proj_transform','camera_center','cam_plane_2_img']
        return {
          'forward_arguments':{'routine':'one_step -> _preprocess -> encode_decode -> _encode_decode_train',
            'source':113,'target':123,'rollout':1,'register_norm':True,'epoch_iter_arguments':'not accepted by this direct routine; same for S/A/B',
            'grad_enabled':torch.is_grad_enabled()},
          'module_modes':{n:m.training for n,m in model.named_modules()},
          'parameters':{n:inspect_value(p) for n,p in model.named_parameters()},
          'registered_buffers':{n:inspect_value(p) for n,p in model.named_buffers()},
          'unregistered_module_attributes':plain_modules,
          'scene_dictionaries':{name:inspect_value(vars(gaussian))},
          'scene_init_attributes':{k:inspect_value(getattr(model,k)) if hasattr(model,k) else 'ABSENT' for k in candidate_names},
          'simulator_preprocessor':inspect_value(model.preprocessor),
          'render_pipeline':inspect_value(vars(model.decode_head.render_pipe)),
          'input':inspect_value({**data,'inputs':{**inputs,'cam':[{k:getattr(c,k) for k in camkeys} for c in inputs['cam']]}}),
          'rng':{'torch_cpu':inspect_value(torch.get_rng_state()),'torch_cuda':inspect_value(torch.cuda.get_rng_state()),
                 'numpy':inspect_value(np.random.get_state()),'python':inspect_value(random.getstate())},
          'backend':{'cudnn_benchmark':torch.backends.cudnn.benchmark,'cudnn_deterministic':torch.backends.cudnn.deterministic,
            'matmul_allow_tf32':torch.backends.cuda.matmul.allow_tf32,'cudnn_allow_tf32':torch.backends.cudnn.allow_tf32,
            'deterministic_algorithms':torch.are_deterministic_algorithms_enabled()}}
    active_label=args.label
    def snapshot_file(label):
        path=args.output/f'{active_label}_{label}_state.json';assert not path.exists()
        with torch.no_grad():state=forward_snapshot()
        path.write_text(json.dumps(state,indent=2)+'\n')
        return state
    def fixed_output(label):
        nonlocal active_label
        active_label=label
        model.eval();event('switch_eval',label=label)
        exact(reference['model'],cpu(model.state_dict()),label+'/checkpoint_model_exact')
        exact(reference['optimizer'],cpu(optimizer.state_dict()),label+'/checkpoint_optimizer_exact')
        exact(reference['counters'],{'epoch':runner.epoch,'iter':runner.iter},label+'/counters_exact')
        exact(reference['optimizer_parameter_names'],list(named),label+'/parameter_order')
        for k,v in gaussian_before.items():exact(v,getattr(gaussian,k).detach(),label+'/Gaussian/'+k)
        assert sha(checkpoint)==checkpoint_hash
        report.setdefault('inference_checks',{})[label]={'checkpoint_sha256':checkpoint_hash,
            'model_exact':True,'optimizer_exact':True,'normalizer_exact':True,'gaussian_exact':True,
            'runner_epoch':runner.epoch,'runner_iter':runner.iter,'model_object_id':id(model),
            'normalizer_keys':[k for k in model.state_dict() if '_acc_' in k or '_num_accumulations' in k]}

        before=cpu(model.state_dict());optbefore=cpu(optimizer.state_dict());rtbefore=runtime()
        snapshot_file('before_forward');event('fixed_forward_begin')
        with torch.no_grad():loss,output=one_step()
        snapshot_file('after_forward');event('fixed_forward_end')
        exact(before,cpu(model.state_dict()),'eval_state_unchanged')
        exact(optbefore,cpu(optimizer.state_dict()),'eval_optimizer_unchanged')
        exact(rtbefore,runtime(),'eval_runtime_unchanged')
        finite([loss,output],'fixed_output')
        return cpu({'steps':[output],'loss':loss})
    if args.label=='S':
        assert not checkpoint.exists() and not refpath.exists()
        pre=cpu(model.state_dict())
        # Match T21 no-update forward preceding the known T22 path.
        event('warmup_forward_begin')
        warm_loss,_=one_step()
        event('warmup_forward_end_no_optimizer')
        report['warmup_forward_loss']={k:float(v.detach().mean()) for k,v in warm_loss.items()}
        del warm_loss,_
        from mmcv.runner import Hook
        class FiniteOptimizerGuard(Hook):
            def after_train_iter(self,r):
                event('train_forward_complete')
                r.optimizer.zero_grad(set_to_none=True)
                finite(r.outputs['loss'],'pre_backward_loss')
                report['training_loss']=float(r.outputs['loss'].detach())
                r.outputs['loss'].backward();event('backward_complete')
                grad={n:p.grad for n,p in named.items() if p.grad is not None}
                finite(grad,'pre_step_gradients');assert grad
                report['pre_step_gradients_finite']=True;event('pre_step_gradient_finite')
                report['gradient_norm']=float(sum(g.double().square().sum() for g in grad.values()).sqrt())
                assert report['gradient_norm']>0
                r.optimizer.step();event('optimizer_step_complete')
                finite(model.state_dict(),'post_step_model_and_normalizers')
                finite(optimizer.state_dict(),'post_step_optimizer')
                finite(runtime(),'post_step_runtime')
                report['post_step_all_state_finite']=True;event('post_step_all_state_finite')
        # Validation-only guard replaces the optimizer hook; original checkpoint hook unchanged.
        runner.register_hook(FiniteOptimizerGuard(),priority='ABOVE_NORMAL')
        runner.register_checkpoint_hook(dict(interval=1,by_epoch=True))
        event('runner_one_batch_begin')
        runner.run([[data]],[('train',1)])
        assert checkpoint.exists()
        event('checkpoint_write_completed',path=str(checkpoint),sha256=sha(checkpoint))
        assert runner.iter==1 and runner.epoch==1
        grads=[p.grad for p in model.parameters() if p.grad is not None]
        assert grads and all(torch.isfinite(g).all() for g in grads)
        report['gradient_norm']=float(sum(g.double().square().sum() for g in grads).sqrt())
        assert report['gradient_norm']>0
        assert optimizer.state
        changed=[k for k,v in model.state_dict().items() if not torch.equal(cpu(v),pre[k])]
        assert changed
        reference={'optimizer_parameter_names':list(named),'model':cpu(model.state_dict()),'optimizer':cpu(optimizer.state_dict()),
                   'counters':{'epoch':runner.epoch,'iter':runner.iter},'runtime':runtime(),
                   'immutable':immutable}
        # Oracle contains independently observed live state; real checkpoint is separate.
        torch.save(reference,refpath)
        manifest={'counters':reference['counters'],'runtime':reference['runtime'],
            'model_schema':{k:{'shape':list(v.shape),'dtype':str(v.dtype)} for k,v in reference['model'].items()},
            'optimizer_parameter_names':list(named),'optimizer_state_ids':list(reference['optimizer']['state']),
            'reference_state_sha256':sha(refpath)}
        (args.output/'reference_manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
        ck=torch.load(checkpoint,map_location='cpu',weights_only=False)
        exact(reference['model'],ck['state_dict'],'saved_model')
        exact(reference['optimizer'],ck['optimizer'],'saved_optimizer')
        exact(reference['counters'],{k:ck['meta'][k] for k in ['epoch','iter']},'saved_counters')
        checkpoint_hash=sha(checkpoint)
        torch.save(fixed_output('S0'),args.output/'S0_output.pt');event('S0_saved')
        m0_bundle=(model,optimizer,runner,gaussian,named)
        event('fresh_M1_instantiation_begin_same_process')
        # No reseeding/backends/state intervention. New objects, same config, real resume.
        model=build_simulator(copy.deepcopy(mc)).cuda();model.init_weights()
        named={n:p for n,p in model.named_parameters() if p.requires_grad}
        optimizer=torch.optim.Adam(list(named.values()),**optcfg)
        runner=build_runner(dict(type='EpochRunner',max_epochs=1),default_args=dict(
            model=model,optimizer=optimizer,work_dir=str(args.output),logger=logging.getLogger('t24'),
            meta={'t24':'same-process fresh M1'}))
        gaussian=model.gs_scene_dict[name]
        assert id(model)!=id(m0_bundle[0])
        runner.resume(str(checkpoint),map_location='cpu');event('M1_resume_complete_same_process')
        torch.save(fixed_output('S1'),args.output/'S1_output.pt');event('S1_saved')
        m1_bundle=(model,optimizer,runner,gaussian,named)
        model,optimizer,runner,gaussian,named=m0_bundle
        torch.save(fixed_output('S0_repeat'),args.output/'S0_repeat_output.pt');event('S0_repeat_saved')
        model,optimizer,runner,gaussian,named=m1_bundle
        torch.save(fixed_output('S1_repeat'),args.output/'S1_repeat_output.pt');event('S1_repeat_saved')
        report['same_process_model_ids']={'M0':id(m0_bundle[0]),'M1':id(m1_bundle[0])}

        report.update(training_steps=1,rollout=1,changed_state_keys=len(changed),runner_meta=ck['meta'],
            counters=reference['counters'],runtime=reference['runtime'],optimizer_states=len(optimizer.state))
    else:
        reference=torch.load(refpath,map_location='cpu',weights_only=False)
        exact(reference['optimizer_parameter_names'],list(named),'optimizer_name_order')
        assert any(not torch.equal(cpu(v),reference['model'][k]) for k,v in model.state_dict().items()),'Fresh model must differ'
        # Use actual resume, not the comparison oracle, to restore model and optimizer.
        event('resume_begin',checkpoint_sha256=sha(checkpoint))
        runner.resume(str(checkpoint),map_location='cpu');event('resume_complete')
        exact(reference['model'],cpu(model.state_dict()),'resumed_model')
        exact(reference['optimizer'],cpu(optimizer.state_dict()),'resumed_optimizer')
        exact(reference['counters'],{'epoch':runner.epoch,'iter':runner.iter},'resumed_counters')
        stats=[k for k in reference['model'] if any(t in k for t in ['_acc_count','_acc_sum','_num_accumulations'])]
        assert stats and any(reference['model'][k].abs().sum()>0 for k in stats)
        report.update(model_exact=True,optimizer_exact=True,counters_exact=True,normalizer_exact=True,
            normalizer_keys=stats,runtime_before_reference=reference['runtime'],runtime_after_resume=runtime())
        # Model num_iter/num_epoch are per-forward mirrors, not progression state.
        # They are overwritten before use; runner epoch/iter above are authoritative.
        for k in set(reference['runtime'])-{'num_iter','num_epoch'}:
            exact(reference['runtime'][k],runtime()[k],k)
        assert reference['runtime'].keys()==runtime().keys()
        report['runtime_persistent_exact']=True
        report['transient_counter_note']='model.num_iter/num_epoch are assigned from runner inputs at every forward_train, not serialized. No prediction dependency on old mirror values.'
        checkpoint_hash=sha(checkpoint)
        output=fixed_output('A')
        torch.save(output,args.output/(args.label+'_output.pt'))
        event('fresh_reload_reference_saved')
        exact(reference['immutable'],immutable,'same_input_hashes')

    for k,v in gaussian_before.items():exact(v,getattr(gaussian,k).detach(),k)
    for p,h in immutable.items():assert sha(p)==h,p
    for p,h in report['source_sha256'].items():assert sha(repo/p)==h,p
    event('verification_complete_process_exit_next')
    report.update(input_data_unchanged=True,gaussian_excluded_and_unchanged=True,
        checkpoint={'path':str(checkpoint),'size_bytes':checkpoint.stat().st_size,'sha256':sha(checkpoint)},
        peak_allocated_bytes=torch.cuda.max_memory_allocated(),peak_reserved_bytes=torch.cuda.max_memory_reserved())

if __name__=='__main__':main()
