#!/usr/bin/env python3
"""T24: one guarded T22-style rollout-1 update; real EpochRunner save/resume in separate processes.
Reference .pt files are comparison oracles only, never resume inputs.
All CUDA requires a Slurm allocation. No source patch or future PLY reset.
"""
import argparse, copy, hashlib, json, logging, os, subprocess, sys, time, traceback, types
from pathlib import Path
import numpy as np

def sha(p):
    return hashlib.sha256(Path(p).read_bytes()).hexdigest()

def main():
    ap=argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--workspace',type=Path,required=True)
    ap.add_argument('--output',type=Path,required=True)
    ap.add_argument('--mode',choices=['save','reload'],required=True)
    ap.add_argument('--report-tag',default='',help='Distinct report filename for read-only diagnostic replay')
    args=ap.parse_args()
    assert os.environ.get('SLURM_JOB_ID'), 'CUDA requires Slurm'
    root=args.workspace.resolve(); repo=root/'SoMA'; os.chdir(repo); sys.path.insert(0,str(repo))
    cp=repo/'docs/deform360/contracts/008-pink-cloth/episode_0'
    args.output.mkdir(parents=True,exist_ok=True)
    report_path=args.output/(args.mode+args.report_tag+'_report.json')
    assert not report_path.exists(), 'No overwrite'
    report={'mode':args.mode,'status':'IN_PROGRESS','job_id':os.environ['SLURM_JOB_ID'],
            'pid':os.getpid(),'tool_sha256':sha(__file__), 'seed':5,
            'scope':'New T24 state, not recovery of job 25824',
            'targets':[123], 'head':subprocess.check_output(['git','rev-parse','HEAD'],text=True).strip()}
    started=time.monotonic()
    try:
        execute(args,root,repo,cp,report)
        report['status']='PASS'
    except Exception:
        report['status']='FAIL';report['exception']=traceback.format_exc()
        raise
    finally:
        report['wall_seconds']=time.monotonic()-started
        report_path.write_text(json.dumps(report,indent=2)+'\n')
        print('T24',args.mode,report['status'],flush=True)

def execute(args,root,repo,cp,report):
    import torch
    from mmcv import Config
    from mmcv.runner import build_runner, build_optimizer
    from mmgs.datasets.embodied_dataset import EmbodiedDataset
    from mmgs.models.builder import build_simulator
    import mmgs.core.runner
    assert torch.cuda.is_available()
    report['gpu']=subprocess.check_output(['nvidia-smi','--query-gpu=name,memory.total','--format=csv,noheader'],text=True).strip()
    torch.manual_seed(5);np.random.seed(5);torch.set_num_threads(4)
    torch.backends.cudnn.benchmark=False
    torch.backends.cudnn.deterministic=True
    source_files=['mmgs/models/simulators/gs_simulator_embodied.py','mmgs/models/utils/dgl_graph.py',
        'mmgs/models/heads/acc_decoder.py','mmgs/datasets/embodied_dataset.py']
    report['source_sha256']={p:sha(repo/p) for p in source_files}
    sample_report=json.loads((cp/'dataset_sample_contract.json').read_text())
    env=sample_report['configurations']['A']['env_cfg']
    scene=Path(env['data_dir'])/env['scene_list'][0];name=scene.name
    immutable={str(p):sha(p) for p in scene.rglob('*') if p.is_file() and 'cluster_mask' not in p.parts and 'controller_mask' not in p.parts}
    # Directory links are not traversed by rglob: explicitly hash supervised images.
    for i in range(2):
        for frame in range(0,155,10):
            for p in [scene/'color'/str(i)/f'{frame}.png',scene/'mask'/str(i)/'1'/f'{frame}.png']:
                immutable[str(p)]=sha(p)
    np.random.seed(5);dataset=EmbodiedDataset(env_cfg=env,phase='train');sample=dataset[0]
    assert dataset.idx_mapping[0][2]==[0,1]
    assert sample['inputs']['gs_aligned_frame']==0 and sample['meta']['seq_num'].item()==10
    assert env['split_list'][name]==[[0,155]] and env['frame_gap']==10
    def batch(x):
        if isinstance(x,np.ndarray):return torch.from_numpy(x).unsqueeze(0).cuda()
        if isinstance(x,torch.Tensor):return x.unsqueeze(0).cuda()
        if isinstance(x,dict):return {k:batch(v) for k,v in x.items()}
        if isinstance(x,list):return [batch(v) for v in x]
        return x
    data=batch(sample);inputs=data['inputs'];gt=data['gt_label'];meta=data['meta']
    for cam in inputs['cam']:cam.to_device('cuda')
    # Official stage1 configuration previously generated by path-only relocation.
    cfgpath=root/'environment/soma-stage1-20260923/cloth_lift_stage1_external_data.py'
    cfg=Config.fromfile(str(cfgpath));mc=copy.deepcopy(cfg.model)
    mc['gs_scene']=[dict(name=name,model_path=str(scene/'pi3/gs/point_cloud/iteration_10000/point_cloud.ply'),sh_degree=0,num_seq=1,attr_name='rope')]
    mc['cluster_cfg']=env['cluster_cfg'];mc['controller_cfg']=env['controller_cfg']
    mc['train_cfg'].update(step_initial=1,max_rollout_step=1)
    report['model_config']=dict(mc);report['dataset_env_cfg']=env
    report['config_provenance']={'path':str(cfgpath),'sha256':sha(cfgpath),'basis':'Official cloth_lift stage1 with sample data paths relocated; scene/cluster/controller and rollout only overridden for this check.'}
    model=build_simulator(mc).cuda();model.init_weights();model.train()
    gaussian=model.gs_scene_dict[name];N=len(gaussian.get_xyz);assert N==12861
    gaussian_fields=['_xyz','_features_dc','_features_rest','_opacity','_scaling','_rotation']
    gaussian_before={k:getattr(gaussian,k).detach().clone() for k in gaussian_fields}
    registered={id(p) for p in model.parameters()}
    assert not any(id(getattr(gaussian,k)) in registered for k in gaussian_fields)
    traj=inputs['controller_trajectory'][0].float();assert tuple(traj.shape)==(16,30,3)
    expected=np.load(root/json.loads((cp/'controller_trajectory_contract.json').read_text())['output']['path_relative_to_workspace'],allow_pickle=False)[0:155:10]
    assert torch.equal(traj.cpu(),torch.from_numpy(expected))
    mapping=[[x[0].squeeze(0).long(),x[1].squeeze(0).long()] for x in inputs['p2c_mapping']]
    grouping=json.loads((cp/'controller_grouping_contract.json').read_text())
    for i,v in enumerate(grouping['p2c']):assert mapping[i][0].cpu().tolist()==v

    def cpu(x):
        if torch.is_tensor(x):return x.detach().cpu().clone()
        if isinstance(x,dict):return {k:cpu(v) for k,v in x.items()}
        if isinstance(x,list):return [cpu(v) for v in x]
        if isinstance(x,tuple):return tuple(cpu(v) for v in x)
        return copy.deepcopy(x)
    def exact(a,b,path='state'):
        if torch.is_tensor(a):
            assert torch.is_tensor(b) and a.shape==b.shape and a.dtype==b.dtype,path
            assert torch.isfinite(a).all() and torch.isfinite(b).all(),path
            assert torch.equal(a.cpu(),b.cpu()),path
        elif isinstance(a,dict):
            assert a.keys()==b.keys(),path+' keys'
            for k in a:exact(a[k],b[k],path+'/'+str(k))
        elif isinstance(a,(list,tuple)):
            assert type(a)==type(b) and len(a)==len(b),path
            for i,(x,y) in enumerate(zip(a,b)):exact(x,y,path+'/'+str(i))
        else:assert a==b,(path,a,b)
    def finite(x,path='value'):
        if torch.is_tensor(x):assert torch.isfinite(x).all(),path+' nonfinite'
        elif isinstance(x,dict):
            for k,v in x.items():finite(v,path+'/'+str(k))
        elif isinstance(x,(list,tuple)):
            for i,v in enumerate(x):finite(v,path+'/'+str(i))
    # Match T22 optimizer membership, including exclusion of nontrainable normalizer stats.
    optcfg=dict(cfg.optimizer);assert optcfg.pop('type')=='Adam'
    named={n:p for n,p in model.named_parameters() if p.requires_grad}
    optimizer=torch.optim.Adam(list(named.values()),**optcfg)
    report['optimizer_parameter_names']=list(named)
    assert not any(id(getattr(gaussian,k)) in {id(p) for g in optimizer.param_groups for p in g['params']} for k in gaussian_fields)
    def one_step():
        # Same real preprocessing/encode/decode/loss calls as T21/T22. No surrogate model.
        xyz=gaussian.get_xyz;cov=gaussian.get_covariance()
        attr=model.scene_attr[model._scene_attr_dict[name]].expand(N,-1)
        volume=torch.prod(gaussian.get_scaling*inputs['volume_scalar'].squeeze(0),dim=-1,keepdim=True)
        pin=torch.zeros((N+30,1),device='cuda');pin[:30]=1
        graphs,connections=model._preprocess(xyz.detach(),xyz,xyz,traj[0].detach(),traj[1].detach(),traj[0],
            attr,volume,cov,inputs['external'].squeeze(0),mapping,pin_mask=pin)
        labels=[v[0,1] for v in gt]
        out=model.encode_decode(graphs,connections,gaussian,inputs['cam'],
            cov.detach().clone(),xyz.detach().clone(),30,register_norm=True,
            gt_label=labels,rollout_size=1,cln_gaussian=gaussian,white_bg_list=inputs.get('white_bg'))
        finite(out,'encode_decode')
        losses=out[-1]
        losses.update(model._encode_decode_train(out[4],labels,
            [m[0,1] for m in inputs['controller_img_mask_list']],inputs['bbox'][0,:,1]))
        finite(losses,'loss')
        return losses,{'pred_pos':out[0],'pred_cov':out[1],'render':out[4]}
    runner=build_runner(dict(type='EpochRunner',max_epochs=1),default_args=dict(
        model=model,optimizer=optimizer,work_dir=str(args.output),logger=logging.getLogger('t24'),
        meta={'t24':'new finite rollout1 state','seed':5,'source_targets':[123]}))
    report['absent_runtime_attributes']=[k for k in ['global_step','iters_per_epoch'] if not hasattr(model,k)]
    checkpoint=args.output/'epoch_1.pth'
    refpath=args.output/'reference_state.pt'
    outputpath=args.output/'reference_output.pt'
    def runtime():
        return {k:getattr(model,k) for k in ['num_iter','num_epoch','global_step','iters_per_epoch','is_est_vel'] if hasattr(model,k)}
    def fixed_output():
        model.eval()
        before=cpu(model.state_dict());optbefore=cpu(optimizer.state_dict());rtbefore=runtime()
        with torch.no_grad():loss,output=one_step()
        exact(before,cpu(model.state_dict()),'eval_state_unchanged')
        exact(optbefore,cpu(optimizer.state_dict()),'eval_optimizer_unchanged')
        exact(rtbefore,runtime(),'eval_runtime_unchanged')
        finite([loss,output],'fixed_output')
        return cpu({'steps':[output],'loss':loss})
    if args.mode=='save':
        assert not checkpoint.exists() and not refpath.exists()
        pre=cpu(model.state_dict())
        # Match T21 no-update forward preceding the known T22 path.
        warm_loss,_=one_step()
        report['warmup_forward_loss']={k:float(v.detach().mean()) for k,v in warm_loss.items()}
        del warm_loss,_
        from mmcv.runner import Hook
        class FiniteOptimizerGuard(Hook):
            def after_train_iter(self,r):
                r.optimizer.zero_grad(set_to_none=True)
                finite(r.outputs['loss'],'pre_backward_loss')
                report['training_loss']=float(r.outputs['loss'].detach())
                r.outputs['loss'].backward()
                grad={n:p.grad for n,p in named.items() if p.grad is not None}
                finite(grad,'pre_step_gradients');assert grad
                report['pre_step_gradients_finite']=True
                report['gradient_norm']=float(sum(g.double().square().sum() for g in grad.values()).sqrt())
                assert report['gradient_norm']>0
                r.optimizer.step()
                finite(model.state_dict(),'post_step_model_and_normalizers')
                finite(optimizer.state_dict(),'post_step_optimizer')
                finite(runtime(),'post_step_runtime')
                report['post_step_all_state_finite']=True
        # Validation-only guard replaces the optimizer hook; original checkpoint hook unchanged.
        runner.register_hook(FiniteOptimizerGuard(),priority='ABOVE_NORMAL')
        runner.register_checkpoint_hook(dict(interval=1,by_epoch=True))
        runner.run([[data]],[('train',1)])
        assert runner.iter==1 and runner.epoch==1
        grads=[p.grad for p in model.parameters() if p.grad is not None]
        assert grads and all(torch.isfinite(g).all() for g in grads)
        report['gradient_norm']=float(sum(g.double().square().sum() for g in grads).sqrt())
        assert report['gradient_norm']>0
        assert optimizer.state
        changed=[k for k,v in model.state_dict().items() if not torch.equal(cpu(v),pre[k])]
        assert changed
        reference={'optimizer_parameter_names':list(named),'model':cpu(model.state_dict()),'optimizer':cpu(optimizer.state_dict()),
                   'counters':{'epoch':runner.epoch,'iter':runner.iter},'runtime':runtime(),
                   'immutable':immutable}
        # Oracle contains independently observed live state; real checkpoint is separate.
        torch.save(reference,refpath)
        manifest={'counters':reference['counters'],'runtime':reference['runtime'],
            'model_schema':{k:{'shape':list(v.shape),'dtype':str(v.dtype)} for k,v in reference['model'].items()},
            'optimizer_parameter_names':list(named),'optimizer_state_ids':list(reference['optimizer']['state']),
            'reference_state_sha256':sha(refpath)}
        (args.output/'reference_manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
        ck=torch.load(checkpoint,map_location='cpu',weights_only=False)
        exact(reference['model'],ck['state_dict'],'saved_model')
        exact(reference['optimizer'],ck['optimizer'],'saved_optimizer')
        exact(reference['counters'],{k:ck['meta'][k] for k in ['epoch','iter']},'saved_counters')
        torch.save(fixed_output(),outputpath)
        report.update(training_steps=1,rollout=1,changed_state_keys=len(changed),runner_meta=ck['meta'],
            counters=reference['counters'],runtime=reference['runtime'],optimizer_states=len(optimizer.state))
    else:
        reference=torch.load(refpath,map_location='cpu',weights_only=False)
        exact(reference['optimizer_parameter_names'],list(named),'optimizer_name_order')
        assert any(not torch.equal(cpu(v),reference['model'][k]) for k,v in model.state_dict().items()),'Fresh model must differ'
        # Use actual resume, not the comparison oracle, to restore model and optimizer.
        runner.resume(str(checkpoint),map_location='cpu')
        exact(reference['model'],cpu(model.state_dict()),'resumed_model')
        exact(reference['optimizer'],cpu(optimizer.state_dict()),'resumed_optimizer')
        exact(reference['counters'],{'epoch':runner.epoch,'iter':runner.iter},'resumed_counters')
        stats=[k for k in reference['model'] if any(t in k for t in ['_acc_count','_acc_sum','_num_accumulations'])]
        assert stats and any(reference['model'][k].abs().sum()>0 for k in stats)
        report.update(model_exact=True,optimizer_exact=True,counters_exact=True,normalizer_exact=True,
            normalizer_keys=stats,runtime_before_reference=reference['runtime'],runtime_after_resume=runtime())
        # Model num_iter/num_epoch are per-forward mirrors, not progression state.
        # They are overwritten before use; runner epoch/iter above are authoritative.
        for k in set(reference['runtime'])-{'num_iter','num_epoch'}:
            exact(reference['runtime'][k],runtime()[k],k)
        assert reference['runtime'].keys()==runtime().keys()
        report['runtime_persistent_exact']=True
        report['transient_counter_note']='model.num_iter/num_epoch are assigned from runner inputs at every forward_train, not serialized. No prediction dependency on old mirror values.'
        expected=torch.load(outputpath,map_location='cpu',weights_only=False)
        actual=fixed_output();diffs={};failed=[]
        report['output_max_abs_diff']=diffs
        report['output_failed_tolerance']=failed
        report['tolerance']={'atol':1e-5,'rtol':1e-5}
        def close(a,b,path='output'):
            if torch.is_tensor(a):
                assert a.shape==b.shape and a.dtype==b.dtype,path
                assert torch.isfinite(a).all() and torch.isfinite(b).all(),path
                diffs[path]=float((a-b).abs().max()) if a.numel() else 0.
                if not torch.allclose(a,b,atol=1e-5,rtol=1e-5):failed.append(path)
            elif isinstance(a,dict):
                assert a.keys()==b.keys()
                for k in a:close(a[k],b[k],path+'/'+str(k))
            elif isinstance(a,(tuple,list)):
                assert len(a)==len(b)
                for i,(x,y) in enumerate(zip(a,b)):close(x,y,path+'/'+str(i))
            else:assert a==b
        close(expected,actual)
        report['all_output_finite']=True
        report['checkpoint']={'path':str(checkpoint),'size_bytes':checkpoint.stat().st_size,'sha256':sha(checkpoint)}
        for p,h in immutable.items():assert sha(p)==h,p
        report['input_data_unchanged']=True
        for k,v in gaussian_before.items():exact(v,getattr(gaussian,k).detach(),k)
        report['gaussian_excluded_and_unchanged']=True
        assert not failed, 'Fixed-output tolerance failed: '+str(failed)
        report.update(output_max_abs_diff=diffs,tolerance={'atol':1e-5,'rtol':1e-5},
            counters={'epoch':runner.epoch,'iter':runner.iter},optimizer_states=len(optimizer.state))
        exact(reference['immutable'],immutable,'same_input_hashes')
        report['reference_manifest_sha256']=sha(args.output/'reference_manifest.json')
    for k,v in gaussian_before.items():exact(v,getattr(gaussian,k).detach(),k)
    for p,h in immutable.items():assert sha(p)==h,p
    for p,h in report['source_sha256'].items():assert sha(repo/p)==h,p
    report.update(input_data_unchanged=True,gaussian_excluded_and_unchanged=True,
        checkpoint={'path':str(checkpoint),'size_bytes':checkpoint.stat().st_size,'sha256':sha(checkpoint)},
        peak_allocated_bytes=torch.cuda.max_memory_allocated(),peak_reserved_bytes=torch.cuda.max_memory_reserved())

if __name__=='__main__':main()
