#!/usr/bin/env python3
"""Strict T20 -> T21 -> T22 -> T23 gates; stop on first exception.

Uses original SoMA preprocessing, encode/decode/loss and forward_train.
Observation wrappers in T23 delegate unchanged arguments/results; no source edits.
"""
import argparse
import copy
import hashlib
import json
import os
from pathlib import Path
import subprocess
import sys
import time
import traceback
import types

import numpy as np


def sha(p):
    return hashlib.sha256(Path(p).read_bytes()).hexdigest()


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--workspace',type=Path,required=True)
    parser.add_argument('--report',type=Path,required=True)
    args=parser.parse_args()
    assert os.environ.get('SLURM_JOB_ID') and not args.report.exists()
    root=args.workspace.resolve();repo=root/'SoMA';os.chdir(repo);sys.path.insert(0,str(repo))
    cp=repo/'docs/deform360/contracts/008-pink-cloth/episode_0'
    report={'stages':{t:{'status':'TODO'} for t in ['T20','T21','T22','T23']},
        'job_id':os.environ['SLURM_JOB_ID'],'tool_sha256':sha(Path(__file__)),
        'scope':'Config A only. Stop first failure. No checkpoint or production training.',
        'head':subprocess.check_output(['git','rev-parse','HEAD'],text=True).strip()}
    stage='T20';start=time.monotonic();torch=None
    def save():args.report.write_text(json.dumps(report,indent=2)+'\n')
    try:
        import torch
        from mmcv import Config
        from mmgs.datasets.embodied_dataset import EmbodiedDataset
        from mmgs.models.builder import build_simulator
        report['gpu']=subprocess.check_output(['nvidia-smi','--query-gpu=name,memory.total','--format=csv,noheader'],text=True).strip()
        assert torch.cuda.is_available()
        torch.manual_seed(5);np.random.seed(5);torch.set_num_threads(4)
        source_files=['mmgs/models/simulators/gs_simulator_embodied.py','mmgs/models/utils/dgl_graph.py',
            'mmgs/models/heads/acc_decoder.py','mmgs/datasets/embodied_dataset.py']
        report['source_sha256']={p:sha(repo/p) for p in source_files}
        sample_report=json.loads((cp/'dataset_sample_contract.json').read_text())
        env=sample_report['configurations']['A']['env_cfg']
        scene=Path(env['data_dir'])/env['scene_list'][0];name=scene.name
        immutable={str(p):sha(p) for p in scene.rglob('*') if p.is_file() and 'cluster_mask' not in p.parts and 'controller_mask' not in p.parts}
        # Directory links are not traversed by rglob: explicitly hash supervised images.
        for i in range(2):
            for frame in range(0,155,10):
                for p in [scene/'color'/str(i)/f'{frame}.png',scene/'mask'/str(i)/'1'/f'{frame}.png']:
                    immutable[str(p)]=sha(p)
        np.random.seed(5);dataset=EmbodiedDataset(env_cfg=env,phase='train');sample=dataset[0]
        assert dataset.idx_mapping[0][2]==[0,1]
        assert sample['inputs']['gs_aligned_frame']==0 and sample['meta']['seq_num'].item()==10
        assert env['split_list'][name]==[[0,155]] and env['frame_gap']==10
        def batch(x):
            if isinstance(x,np.ndarray):return torch.from_numpy(x).unsqueeze(0).cuda()
            if isinstance(x,torch.Tensor):return x.unsqueeze(0).cuda()
            if isinstance(x,dict):return {k:batch(v) for k,v in x.items()}
            if isinstance(x,list):return [batch(v) for v in x]
            return x
        data=batch(sample);inputs=data['inputs'];gt=data['gt_label'];meta=data['meta']
        for cam in inputs['cam']:cam.to_device('cuda')
        # Official stage1 configuration previously generated by path-only relocation.
        cfgpath=root/'environment/soma-stage1-20260923/cloth_lift_stage1_external_data.py'
        cfg=Config.fromfile(str(cfgpath));mc=copy.deepcopy(cfg.model)
        mc['gs_scene']=[dict(name=name,model_path=str(scene/'pi3/gs/point_cloud/iteration_10000/point_cloud.ply'),sh_degree=0,num_seq=1,attr_name='rope')]
        mc['cluster_cfg']=env['cluster_cfg'];mc['controller_cfg']=env['controller_cfg']
        mc['train_cfg'].update(step_initial=1,max_rollout_step=1)
        report['model_config']=dict(mc);report['dataset_env_cfg']=env
        report['config_provenance']={'path':str(cfgpath),'sha256':sha(cfgpath),'basis':'Official cloth_lift stage1 with sample data paths relocated; scene/cluster/controller and rollout only overridden for this check.'}
        model=build_simulator(mc).cuda();model.init_weights();model.train()
        gaussian=model.gs_scene_dict[name];N=len(gaussian.get_xyz);assert N==12861
        gaussian_fields=['_xyz','_features_dc','_features_rest','_opacity','_scaling','_rotation']
        gaussian_before={k:getattr(gaussian,k).detach().clone() for k in gaussian_fields}
        registered={id(p) for p in model.parameters()}
        assert not any(id(getattr(gaussian,k)) in registered for k in gaussian_fields)
        traj=inputs['controller_trajectory'][0].float();assert tuple(traj.shape)==(16,30,3)
        expected=np.load(root/json.loads((cp/'controller_trajectory_contract.json').read_text())['output']['path_relative_to_workspace'],allow_pickle=False)[0:155:10]
        assert torch.equal(traj.cpu(),torch.from_numpy(expected))
        mapping=[[x[0].squeeze(0).long(),x[1].squeeze(0).long()] for x in inputs['p2c_mapping']]
        grouping=json.loads((cp/'controller_grouping_contract.json').read_text())
        for i,v in enumerate(grouping['p2c']):assert mapping[i][0].cpu().tolist()==v
        def memory():
            return {'allocated_bytes':torch.cuda.memory_allocated(),'reserved_bytes':torch.cuda.memory_reserved(),
                    'peak_allocated_bytes':torch.cuda.max_memory_allocated(),'peak_reserved_bytes':torch.cuda.max_memory_reserved()}
        def finite(x):
            if isinstance(x,torch.Tensor):assert torch.isfinite(x).all().item(),'NaN/Inf tensor'
            elif isinstance(x,dict):
                for v in x.values():finite(v)
            elif isinstance(x,(list,tuple)):
                for v in x:finite(v)
        def graph_summary(g):
            u,v=g.edges()
            if len(u):assert min(u.min().item(),v.min().item())>=0 and max(u.max().item(),v.max().item())<g.num_nodes()
            for vals in [g.ndata,g.edata]:
                for val in vals.values():finite(val)
            return {'nodes':g.num_nodes(),'edges':g.num_edges(),
                'edge_index_minmax':None if not len(u) else [int(min(u.min(),v.min())),int(max(u.max(),v.max()))],
                'node_features':{k:{'shape':list(v.shape),'dtype':str(v.dtype),'finite':True} for k,v in g.ndata.items()},
                'edge_features':{k:{'shape':list(v.shape),'dtype':str(v.dtype),'finite':True} for k,v in g.edata.items()}}
        def preprocess():
            xyz=gaussian.get_xyz;cov=gaussian.get_covariance()
            attr=model.scene_attr[model._scene_attr_dict[name]].expand(N,-1)
            volume=torch.prod(gaussian.get_scaling*inputs['volume_scalar'].squeeze(0),dim=-1,keepdim=True)
            pin=torch.zeros((N+30,1),device='cuda');pin[:30]=1
            return model._preprocess(xyz.detach(),xyz,xyz,traj[0].detach(),traj[1].detach(),traj[0],
                attr,volume,cov,inputs['external'].squeeze(0),mapping,pin_mask=pin)
        torch.cuda.reset_peak_memory_stats()
        graphs,connections=preprocess()
        assert len(graphs)==4 and len(connections)==3
        layers=[]
        for i,g in enumerate(graphs):
            s=graph_summary(g);pin=g.ndata['pin_mask'].reshape(-1)
            count=[30,10,2,1][i];assert int((pin==1).sum())==count
            assert torch.all(pin[:count]==1) and torch.all(pin[count:]==0)
            s.update(controller_nodes=count,object_nodes=g.num_nodes()-count,layer=i)
            layers.append(s)
        maps=[]
        for i,(controller,obj) in enumerate(mapping):
            merged=torch.cat([controller,obj]);assert merged.min()>=0
            if i<len(connections):
                assert len(merged)==graphs[i].num_nodes()
                assert merged.max()<graphs[i+1].num_nodes()
                assert torch.equal(torch.unique(merged),torch.arange(graphs[i+1].num_nodes(),device='cuda'))
            maps.append({'controller_shape':list(controller.shape),'object_shape':list(obj.shape),
                         'min':int(merged.min()),'max':int(merged.max())})
        assert torch.equal(graphs[0].ndata['cur_state'][30:],gaussian.get_xyz)
        assert torch.equal(graphs[0].ndata['cur_state'][:30],traj[1])
        report['stages']['T20'].update(status='PASS',seconds=time.monotonic()-start,layers=layers,
            connections=[graph_summary(g) for g in connections],p2c=maps,
            controller_hierarchy=[30,10,2,1],Gaussian_identity_unchanged=True,memory=memory())
        save();print('T20 PASS',json.dumps([(x['object_nodes'],x['controller_nodes'],x['edges']) for x in layers]),flush=True)

        def losses_json(losses):
            finite(losses);return {k:float(v.detach().mean()) for k,v in losses.items()}
        def total_loss(losses):
            result=sum(v.mean() for k,v in losses.items() if k.startswith('decode.loss'))
            finite(result);assert result.requires_grad
            return result
        def one_step(graphs,connections,rollout=1):
            labels=[v[0,1] for v in gt]
            out=model.encode_decode(graphs,connections,gaussian,inputs['cam'],
                gaussian.get_covariance().detach().clone(),gaussian.get_xyz.detach().clone(),30,
                register_norm=True,gt_label=labels,rollout_size=rollout,cln_gaussian=gaussian,
                white_bg_list=inputs.get('white_bg'))
            pred,cov,dg,knowledge,images,depths,loss=out
            finite([pred,cov,dg,knowledge,images,depths,loss])
            assert tuple(pred.shape)==(N+30,3) and all(tuple(x.shape)==(3,360,640) for x in images)
            loss.update(model._encode_decode_train(images,labels,[m[0,1] for m in inputs['controller_img_mask_list']],inputs['bbox'][0,:,1]))
            return loss,{'input_source':113,'target_source':123,'target_local':10,
                'controller_prev_source':113,'controller_cur_source':123,'object_shape':[N,3],
                'render_shapes':[list(x.shape) for x in images],'losses':losses_json(loss),'memory':memory()}
        stage='T21';start=time.monotonic();torch.cuda.reset_peak_memory_stats()
        losses,summary=one_step(graphs,connections)
        total=total_loss(losses);summary['total_loss']=float(total.detach())
        report['stages'][stage].update(status='PASS',seconds=time.monotonic()-start,**summary)
        save();print('T21 PASS',summary['total_loss'],flush=True)
        del graphs,connections,losses,total

        stage='T22';start=time.monotonic();torch.cuda.reset_peak_memory_stats()
        named={n:p for n,p in model.named_parameters() if p.requires_grad}
        optcfg=dict(cfg.optimizer);kind=optcfg.pop('type');assert kind=='Adam'
        optimizer=torch.optim.Adam(list(named.values()),**optcfg)
        assert {id(p) for group in optimizer.param_groups for p in group['params']}=={id(p) for p in named.values()}
        assert not any(id(getattr(gaussian,k)) in {id(p) for p in named.values()} for k in gaussian_fields)
        report['optimizer']={'type':kind,**optcfg,'parameter_names':list(named),'scene_gaussians_excluded':True}
        before={n:p.detach().clone() for n,p in named.items()}
        optimizer.zero_grad(set_to_none=True)
        graphs,connections=preprocess();losses,summary=one_step(graphs,connections)
        total=total_loss(losses);total.backward()
        def gradients():
            norms={};zero=[];missing=[]
            for n,p in named.items():
                if p.grad is None:missing.append(n);continue
                finite(p.grad);norm=float(p.grad.detach().double().norm())
                if norm: norms[n]=norm
                else:zero.append(n)
            assert any(n.startswith('backbone.') for n in norms),'No dynamics backbone gradient'
            return {'global_norm':float(sum(v*v for v in norms.values())**0.5),'nonzero':norms,'zero':zero,'missing':missing}
        grads=gradients();optimizer.step()
        changed={}
        for n,p in named.items():
            finite(p);delta=float((p.detach()-before[n]).abs().max())
            if delta:changed[n]=delta
        assert any(n.startswith('backbone.') for n in changed)
        for k,v in gaussian_before.items():assert torch.equal(v,getattr(gaussian,k).detach())
        report['stages'][stage].update(status='PASS',seconds=time.monotonic()-start,
            total_loss=float(total.detach()),gradients=grads,changed_parameters_max_abs=changed,memory=memory())
        save();print('T22 PASS grad_norm',grads['global_norm'],flush=True)
        del graphs,connections,losses,total,before

        stage='T23';start=time.monotonic();torch.cuda.reset_peak_memory_stats()
        model.train_cfg.update(step_initial=3,max_rollout_step=3)
        optimizer.zero_grad(set_to_none=True)
        steps=[];last_pred=None;last_cur=None
        original_pre=model._preprocess;original_encode=model.encode_decode;original_loss=model._encode_decode_train
        def observe_pre(self,*args,**kwargs):
            nonlocal last_cur
            step=len(steps);assert step<3
            prev,cur,template,controller_prev,controller_cur=args[:5]
            if step==0:assert torch.equal(cur,gaussian.get_xyz)
            else:
                assert torch.equal(cur,last_pred),'Autoregressive mismatch'
                assert torch.equal(prev,last_cur),'Previous-state mismatch'
                assert cur.requires_grad==model.accumulate_gradient
            assert torch.equal(template,gaussian.get_xyz)
            assert torch.equal(controller_prev,traj[step]) and torch.equal(controller_cur,traj[step+1])
            finite(args[:11]);last_cur=cur.detach().clone()
            steps.append({'step':step+1,'input_state_source':'initial source113' if step==0 else f'prediction step{step}',
                          'controller_source_pair':[113+10*step,123+10*step],
                          'target_source':123+10*step,'target_local':10*(step+1),
                          'input_object_shape':list(cur.shape),'state_transfer_verified':True})
            return original_pre(*args,**kwargs)
        def observe_encode(self,*args,**kwargs):
            nonlocal last_pred
            i=len(steps)
            for actual,expected in zip(kwargs['gt_label'],gt):assert torch.equal(actual,expected[0,i])
            out=original_encode(*args,**kwargs)
            finite(out);pred=out[0];assert tuple(pred.shape)==(N+30,3)
            last_pred=pred[30:].detach().clone()
            steps[-1].update(predicted_object_shape=list(last_pred.shape),render_shapes=[list(x.shape) for x in out[4]],
                             regularization=losses_json(out[-1]),memory=memory())
            return out
        def observe_loss(self,*args,**kwargs):
            result=original_loss(*args,**kwargs);steps[-1]['image_losses']=losses_json(result);return result
        model._preprocess=types.MethodType(observe_pre,model)
        model.encode_decode=types.MethodType(observe_encode,model)
        model._encode_decode_train=types.MethodType(observe_loss,model)
        losses=model.forward_train(inputs,gt,meta=meta,num_epoch=0,num_iter=0)
        assert len(steps)==3
        total=total_loss(losses);total.backward();grads=gradients()
        for k,v in gaussian_before.items():assert torch.equal(v,getattr(gaussian,k).detach())
        report['stages'][stage].update(status='PASS',seconds=time.monotonic()-start,steps=steps,
            total_loss=float(total.detach()),losses=losses_json(losses),gradients=grads,
            accumulate_gradient=model.accumulate_gradient,optimizer_step=False,memory=memory(),
            weights='Same instance after the single T22 optimizer update; no reload/reset.')
        for path,h in immutable.items():assert sha(path)==h,'Input data changed'
        for path,h in report['source_sha256'].items():assert sha(repo/path)==h,'Source code changed'
        report['immutable_data_sha256']=immutable;report['input_data_unchanged']=True
        save();print('T23 PASS',float(total.detach()),flush=True)
    except Exception:
        report['stages'][stage].update(status='FAIL',seconds=time.monotonic()-start,exception=traceback.format_exc())
        if torch is not None and torch.cuda.is_initialized():
            report['stages'][stage]['failure_memory']={'allocated':torch.cuda.memory_allocated(),'reserved':torch.cuda.memory_reserved(),'peak_allocated':torch.cuda.max_memory_allocated()}
        save();print('BATCH STOP',stage,report['stages'][stage]['exception'],flush=True)
        raise


if __name__=='__main__':main()
