# T25 frozen SoMA-D360-v0 Config A Stage-1 baseline (2026-09-26).
# Training/model settings inherit audited cloth_lift_stage1.py at 8e8772a.
# Interface overrides are from T0-T24 contracts; no sample file is read at load.
# Run tools/train.py with --seed 5: its CLI overwrites cfg.seed.
# data.val AND data.test here are TRAIN-ONLY diagnostic routes, not holdout.
# Holdout source [268,307) is reserved for later continuous-rollout tasks.
# No future reconstructed PLY reset. Do not silently cap the rollout curriculum.
_base_ = ['../_base_/models/gs_simulator_embodied.py',
 '../_base_/datasets/gs_soma_dataloader.py',
 '../_base_/schedules/adam_hood.py',
 '../_base_/default_runtime.py']

seed = 5

max_seq = 1

find_unused_parameters = True

model = {'pred_vel': True,
 'use_rotation': False,
 'fix_bug': True,
 'dt': 0.06666666666666667,
 'cluster_cfg': {'_delete_': True,
                 'config_a_2cam': [{'downsample_rate': 0.02}, {'downsample_rate': 0.2}]},
 'controller_cfg': {'config_a_2cam': [{'num_cluster': 10}, {'downsample_rate': 0.5}]},
 'checkpoint_rollout': 20,
 'gs_scene': [{'name': 'config_a_2cam',
               'model_path': '/data1/userdata/tcweng/projects/tcgs/datasets/deform360/derived/t17_scene_packages/pink_cloth_episode_0/config_a_2cam/pi3/gs/point_cloud/iteration_10000/point_cloud.ply',
               'sh_degree': 0,
               'num_seq': 1,
               'attr_name': 'rope'}],
 'processor_cfg': [{'type': 'GsHieEmbodiedDGLProcessor',
                    'anchor_prefix': 'anchor_',
                    'radius': [0.03, 0.2, 0.5],
                    'group_cfg': {'max_radius': None,
                                  'min_radius': 0.0,
                                  'sample_num': 16,
                                  'use_xyz': True,
                                  'normalize_xyz': False,
                                  'return_grouped_xyz': False,
                                  'return_grouped_idx': True,
                                  'return_unique_cnt': False}}],
 'opt_sim': True,
 'opt_vel': True,
 'static_loss': False,
 'selfsup_loss': False,
 'avg_loss': True,
 'render_mov_only': True,
 'train_cfg': {'by_epoch': True,
               'step_increase_interval': 1,
               'step_increase_magnitude': 3,
               'step_initial': 3,
               'max_rollout_step': 1000},
 'test_cfg': {'by_epoch': True,
              'step_increase_interval': 1,
              'step_increase_magnitude': 3,
              'step_initial': 3,
              'max_rollout_step': 1000},
 'backbone': {'fix_bug': True, 'num_encoder_layers': 16, 'edge_theta': True, 'num_fcs': 3},
 'decode_head': {'loss_decode': [{'type': 'MSELoss',
                                  'reduction': 'sum',
                                  'loss_weight': 1.0,
                                  'loss_name': 'loss_mse_momentum'},
                                 {'type': 'SSIMLoss',
                                  'reduction': 'sum',
                                  'kernel_size': 5,
                                  'loss_weight': 0.1,
                                  'loss_name': 'loss_ssim_render'},
                                 {'type': 'L2Loss',
                                  'reduction': 'sum',
                                  'loss_weight': 0.9,
                                  'loss_name': 'loss_l2_render'},
                                 {'type': 'MSELoss',
                                  'reduction': 'sum',
                                  'loss_weight': 1.0,
                                  'loss_name': 'loss_mse_static'},
                                 {'type': 'SpatialLoss',
                                  'reduction': 'sum',
                                  'loss_weight': 1.0,
                                  'loss_name': 'loss_spatial'},
                                 {'type': 'L2Loss',
                                  'reduction': 'sum',
                                  'loss_weight': 0.9,
                                  'loss_name': 'loss_l2_bounding'},
                                 {'type': 'SSIMLoss',
                                  'reduction': 'sum',
                                  'kernel_size': 5,
                                  'loss_weight': 0.1,
                                  'loss_name': 'loss_ssim_bounding'}]}}

data = {'samples_per_gpu': 1,
 'workers_per_gpu': 0,
 'train': {'type': 'RepeatDataset',
           'times': 50,
           'dataset': {'type': 'EmbodiedDataset',
                       'phase': 'all',
                       'env_cfg': {'data_dir': '/data1/userdata/tcweng/projects/tcgs/datasets/deform360/derived/t17_scene_packages/pink_cloth_episode_0',
                                   'scene_list': ['config_a_2cam'],
                                   'sub_img_dir': 'color',
                                   'sub_video_dir': 'color',
                                   'cam_transform_fn': None,
                                   'resolution': [360, 640],
                                   'load_imgs': False,
                                   'scale_x_angle': 1.0,
                                   'max_cam_num': 2,
                                   'max_cam_total': 2,
                                   'max_seq': 1,
                                   'pad_cam': False,
                                   'llffhold': 0,
                                   'tracking_pcd': 'track_process_data.pkl',
                                   'prompt_dict': {'object': ['cloth'], 'obstacle': []},
                                   'bounding_box': None,
                                   'use_random_background': {'config_a_2cam': False},
                                   'const_white_bg': {'config_a_2cam': False},
                                   'controller_cfg': {'config_a_2cam': [{'num_cluster': 10},
                                                                        {'downsample_rate': 0.5}]},
                                   'cluster_type': 'dis_split',
                                   'gravity': [0.0, 0.0, -9.8],
                                   'rot_est': {'config_a_2cam': [0.0, 0.0, 0.0, 1.0]},
                                   'dt': 0.03333333333333333,
                                   'real_dt': {'config_a_2cam': 0.06666666666666667},
                                   'split_list': {'config_a_2cam': [[0, 155]]},
                                   'frame_gap': 10,
                                   'cluster_cfg': {'config_a_2cam': [{'downsample_rate': 0.02},
                                                                     {'downsample_rate': 0.2}]},
                                   'volume_scalar': {'config_a_2cam': 512},
                                   '_delete_': True,
                                   'aligned_scene': None,
                                   'max_frame': 1001,
                                   'start_frame': 0}}},
 'val': {'type': 'EmbodiedDataset',
         'phase': 'all',
         'env_cfg': {'data_dir': '/data1/userdata/tcweng/projects/tcgs/datasets/deform360/derived/t17_scene_packages/pink_cloth_episode_0',
                     'scene_list': ['config_a_2cam'],
                     'sub_img_dir': 'color',
                     'sub_video_dir': 'color',
                     'cam_transform_fn': None,
                     'resolution': [360, 640],
                     'load_imgs': False,
                     'scale_x_angle': 1.0,
                     'max_cam_num': 2,
                     'max_cam_total': 2,
                     'max_seq': 1,
                     'pad_cam': False,
                     'llffhold': 0,
                     'tracking_pcd': 'track_process_data.pkl',
                     'prompt_dict': {'object': ['cloth'], 'obstacle': []},
                     'bounding_box': None,
                     'use_random_background': {'config_a_2cam': False},
                     'const_white_bg': {'config_a_2cam': False},
                     'controller_cfg': {'config_a_2cam': [{'num_cluster': 10},
                                                          {'downsample_rate': 0.5}]},
                     'cluster_type': 'dis_split',
                     'gravity': [0.0, 0.0, -9.8],
                     'rot_est': {'config_a_2cam': [0.0, 0.0, 0.0, 1.0]},
                     'dt': 0.03333333333333333,
                     'real_dt': {'config_a_2cam': 0.06666666666666667},
                     'split_list': {'config_a_2cam': [[0, 155]]},
                     'frame_gap': 10,
                     'cluster_cfg': {'config_a_2cam': [{'downsample_rate': 0.02},
                                                       {'downsample_rate': 0.2}]},
                     'volume_scalar': {'config_a_2cam': 512},
                     '_delete_': True,
                     'aligned_scene': None,
                     'max_frame': 1003,
                     'start_frame': 0,
                     'eval_start_frame': -1}},
 'test': {'type': 'EmbodiedDataset',
          'phase': 'all',
          'env_cfg': {'data_dir': '/data1/userdata/tcweng/projects/tcgs/datasets/deform360/derived/t17_scene_packages/pink_cloth_episode_0',
                      'scene_list': ['config_a_2cam'],
                      'sub_img_dir': 'color',
                      'sub_video_dir': 'color',
                      'cam_transform_fn': None,
                      'resolution': [360, 640],
                      'load_imgs': False,
                      'scale_x_angle': 1.0,
                      'max_cam_num': 2,
                      'max_cam_total': 2,
                      'max_seq': 1,
                      'pad_cam': False,
                      'llffhold': 0,
                      'tracking_pcd': 'track_process_data.pkl',
                      'prompt_dict': {'object': ['cloth'], 'obstacle': []},
                      'bounding_box': None,
                      'use_random_background': {'config_a_2cam': False},
                      'const_white_bg': {'config_a_2cam': False},
                      'controller_cfg': {'config_a_2cam': [{'num_cluster': 10},
                                                           {'downsample_rate': 0.5}]},
                      'cluster_type': 'dis_split',
                      'gravity': [0.0, 0.0, -9.8],
                      'rot_est': {'config_a_2cam': [0.0, 0.0, 0.0, 1.0]},
                      'dt': 0.03333333333333333,
                      'real_dt': {'config_a_2cam': 0.06666666666666667},
                      'split_list': {'config_a_2cam': [[0, 155]]},
                      'frame_gap': 10,
                      'cluster_cfg': {'config_a_2cam': [{'downsample_rate': 0.02},
                                                        {'downsample_rate': 0.2}]},
                      'volume_scalar': {'config_a_2cam': 512},
                      '_delete_': True,
                      'aligned_scene': None,
                      'max_frame': 1003,
                      'start_frame': 0,
                      'eval_start_frame': -1}}}

optimizer = {'type': 'Adam', 'lr': 0.0004, 'betas': (0.9, 0.999), 'weight_decay': 0, 'amsgrad': False}

lr_config = {'by_epoch': True, 'policy': 'Hood', 'decay_rate': 0.5, 'decay_steps': 2, 'step_start': 14}

runner = {'type': 'EpochRunner', 'max_epochs': 46, 'max_iters': None}

checkpoint_config = {'by_epoch': True, 'interval': 1, 'max_keep_ckpts': 10000}

evaluation = {'by_epoch': True, 'interval': 1}

work_dir = '/data1/userdata/tcweng/projects/tcgs/outputs/deform360/stage1/config_a_seed5/'

load_from = None

resume_from = None
