# T30.1 frozen Stage-2 Config A protocol; no training authorized by this file.
# Full model/interface values match T29 validated expanded official Stage-2 model.
# Fresh runner k=0..60 corresponds to official runner epoch 15+k (not fake counters).
# rollout: 3*k+3; Hood: .0004*(.5**((k+1)//2)+.01), including the original .01 floor.
# 15 windows * repeat40 / batch1 / GPU1 = 600 updates/epoch; total 36600.
# Final selection: epoch_61.pth, never test-selected. No save_best hook.
# load_from loads model state incl. learned FP64 Normalizer; NOT Stage-1 Adam/counters.
# Run tools/train.py with --seed 5 (CLI overwrites cfg.seed); do NOT pass --resume-from.
# Both val/test routes below are TRAIN-ONLY segmented diagnostics, not T31 holdout.
# Fixed T27 cached starts: both online Gaussian update flags false; never future PLY.
_base_ = ['../_base_/schedules/adam_hood.py', '../_base_/default_runtime.py']

seed = 5

# Official entrypoint sequence-cap sentinel; windows remain defined by split_list.
max_seq = 1

find_unused_parameters = True

model = {'type': 'GsSimulatorEmbodiedS2',
 'cluster_cfg': {'config_a_2cam': [{'downsample_rate': 0.02}, {'downsample_rate': 0.2}]},
 'processor_cfg': [{'type': 'GsHieEmbodiedDGLProcessor',
                    'anchor_prefix': 'anchor_',
                    'radius': [0.03, 0.2, 0.5],
                    'group_cfg': {'max_radius': None,
                                  'min_radius': 0.0,
                                  'sample_num': 16,
                                  'use_xyz': True,
                                  'normalize_xyz': False,
                                  'return_grouped_xyz': False,
                                  'return_grouped_idx': True,
                                  'return_unique_cnt': False}}],
 'accumulate_gradient': False,
 'dt': 0.06666666666666667,
 'backbone': {'type': 'MeshGraphNetHieEmbodied',
              'attr_dim': 5,
              'state_dim': 6,
              'position_dim': 3,
              'num_frames': 2,
              'embed_dims': 128,
              'num_encoder_layers': 16,
              'dropout': 0.0,
              'eps': 1e-07,
              'num_fcs': 3,
              'act_cfg': {'type': 'SiLU', 'inplace': True},
              'norm_cfg': {'type': 'LN'},
              'pre_norm': True,
              'norm_acc_steps': None,
              'edge_mode': 'ratio',
              'edge_theta': True,
              'fix_bug': True,
              'dt': 0.06666666666666667},
 'decode_head': {'type': 'AccDecoder',
                 'in_channels': 128,
                 'out_channels': 11,
                 'add_residual': False,
                 'init_quant': 1.0,
                 'loss_decode': [{'type': 'MSELoss',
                                  'reduction': 'sum',
                                  'loss_weight': 1.0,
                                  'loss_name': 'loss_mse_momentum'},
                                 {'type': 'SSIMLoss',
                                  'reduction': 'sum',
                                  'kernel_size': 5,
                                  'loss_weight': 0.1,
                                  'loss_name': 'loss_ssim_render'},
                                 {'type': 'L2Loss',
                                  'reduction': 'sum',
                                  'loss_weight': 0.9,
                                  'loss_name': 'loss_l2_render'},
                                 {'type': 'MSELoss',
                                  'reduction': 'sum',
                                  'loss_weight': 1.0,
                                  'loss_name': 'loss_mse_static'},
                                 {'type': 'SpatialLoss',
                                  'reduction': 'sum',
                                  'loss_weight': 1.0,
                                  'loss_name': 'loss_spatial'},
                                 {'type': 'L2Loss',
                                  'reduction': 'sum',
                                  'loss_weight': 0.9,
                                  'loss_name': 'loss_l2_bounding'},
                                 {'type': 'SSIMLoss',
                                  'reduction': 'sum',
                                  'kernel_size': 5,
                                  'loss_weight': 0.1,
                                  'loss_name': 'loss_ssim_bounding'}],
                 'accuracy': [{'type': 'L2Accuracy',
                               'reduction': 'mean',
                               'acc_name': 'acc_l2_render'},
                              {'type': 'L1Accuracy',
                               'reduction': 'mean',
                               'acc_name': 'acc_l1_render'},
                              {'type': 'SSIMAccuracy',
                               'reduction': 'mean',
                               'acc_name': 'acc_ssim_render'},
                              {'type': 'PSNRAccuracy',
                               'reduction': 'mean',
                               'acc_name': 'acc_psnr_render'}],
                 'dt': 0.06666666666666667},
 'gs_scene': [{'name': 'config_a_2cam',
               'model_path': '/data1/userdata/tcweng/projects/tcgs/datasets/deform360/derived/t17_scene_packages/pink_cloth_episode_0/config_a_2cam/pi3/gs/point_cloud/iteration_10000/point_cloud.ply',
               'sh_degree': 0,
               'num_seq': 1,
               'attr_name': 'rope'}],
 'forward_last_layer': False,
 'share_weight': True,
 'opt_sim': True,
 'opt_vel': True,
 'checkpoint_rollout': 20,
 'selfsup_loss': False,
 'pred_vel': True,
 'use_rotation': False,
 'fix_bug': True,
 'frame_gap': 10,
 'test_rollout_mode': 'segmented',
 'flag_save_gaussian': False,
 'flag_update_gaussian': False,
 'flag_update_gaussian_train': False,
 'data_dir': '/data1/userdata/tcweng/projects/tcgs/datasets/deform360/derived/008-pink-cloth/episode_0/t27_stage1_cache_gap10',
 'controller_cfg': {'config_a_2cam': [{'num_cluster': 10}, {'downsample_rate': 0.5}]},
 'static_loss': False,
 'avg_loss': True,
 'render_mov_only': True,
 'train_cfg': {'by_epoch': True,
               'step_increase_interval': 1,
               'step_increase_magnitude': 3,
               'step_initial': 3,
               'max_rollout_step': 1000},
 'test_cfg': {'by_epoch': True,
              'step_increase_interval': 1,
              'step_increase_magnitude': 3,
              'step_initial': 3,
              'max_rollout_step': 1000}}

data = {'samples_per_gpu': 1,
 'workers_per_gpu': 0,
 'train': {'type': 'RepeatDataset',
           'times': 40,
           'dataset': {'type': 'EmbodiedDataset',
                       'phase': 'all',
                       'env_cfg': {'data_dir': '/data1/userdata/tcweng/projects/tcgs/datasets/deform360/derived/t17_scene_packages/pink_cloth_episode_0',
                                   'scene_list': ['config_a_2cam'],
                                   'sub_img_dir': 'color',
                                   'sub_video_dir': 'color',
                                   'cam_transform_fn': None,
                                   'resolution': [360, 640],
                                   'load_imgs': False,
                                   'scale_x_angle': 1.0,
                                   'max_cam_num': 2,
                                   'max_cam_total': 2,
                                   'max_seq': 15,
                                   'pad_cam': False,
                                   'llffhold': 0,
                                   'tracking_pcd': 'track_process_data.pkl',
                                   'prompt_dict': {'object': ['cloth'], 'obstacle': []},
                                   'bounding_box': None,
                                   'use_random_background': {'config_a_2cam': False},
                                   'const_white_bg': {'config_a_2cam': False},
                                   'controller_cfg': {'config_a_2cam': [{'num_cluster': 10},
                                                                        {'downsample_rate': 0.5}]},
                                   'cluster_type': 'dis_split',
                                   'gravity': [0.0, 0.0, -9.8],
                                   'rot_est': {'config_a_2cam': [0.0, 0.0, 0.0, 1.0]},
                                   'dt': 0.03333333333333333,
                                   'real_dt': {'config_a_2cam': 0.06666666666666667},
                                   'split_list': {'config_a_2cam': [[0, 13],
                                                                    [10, 23],
                                                                    [20, 33],
                                                                    [30, 43],
                                                                    [40, 53],
                                                                    [50, 63],
                                                                    [60, 73],
                                                                    [70, 83],
                                                                    [80, 93],
                                                                    [90, 103],
                                                                    [100, 113],
                                                                    [110, 123],
                                                                    [120, 133],
                                                                    [130, 143],
                                                                    [140, 150]]},
                                   'frame_gap': 1,
                                   'cluster_cfg': {'config_a_2cam': [{'downsample_rate': 0.02},
                                                                     {'downsample_rate': 0.2}]},
                                   'volume_scalar': {'config_a_2cam': 512},
                                   'aligned_scene': None,
                                   'max_frame': 1001,
                                   'start_frame': 0,
                                   'interact': False}}},
 'val': {'type': 'EmbodiedDataset',
         'phase': 'all',
         'env_cfg': {'data_dir': '/data1/userdata/tcweng/projects/tcgs/datasets/deform360/derived/t17_scene_packages/pink_cloth_episode_0',
                     'scene_list': ['config_a_2cam'],
                     'sub_img_dir': 'color',
                     'sub_video_dir': 'color',
                     'cam_transform_fn': None,
                     'resolution': [360, 640],
                     'load_imgs': False,
                     'scale_x_angle': 1.0,
                     'max_cam_num': 2,
                     'max_cam_total': 2,
                     'max_seq': 15,
                     'pad_cam': False,
                     'llffhold': 0,
                     'tracking_pcd': 'track_process_data.pkl',
                     'prompt_dict': {'object': ['cloth'], 'obstacle': []},
                     'bounding_box': None,
                     'use_random_background': {'config_a_2cam': False},
                     'const_white_bg': {'config_a_2cam': False},
                     'controller_cfg': {'config_a_2cam': [{'num_cluster': 10},
                                                          {'downsample_rate': 0.5}]},
                     'cluster_type': 'dis_split',
                     'gravity': [0.0, 0.0, -9.8],
                     'rot_est': {'config_a_2cam': [0.0, 0.0, 0.0, 1.0]},
                     'dt': 0.03333333333333333,
                     'real_dt': {'config_a_2cam': 0.06666666666666667},
                     'split_list': {'config_a_2cam': [[0, 13],
                                                      [10, 23],
                                                      [20, 33],
                                                      [30, 43],
                                                      [40, 53],
                                                      [50, 63],
                                                      [60, 73],
                                                      [70, 83],
                                                      [80, 93],
                                                      [90, 103],
                                                      [100, 113],
                                                      [110, 123],
                                                      [120, 133],
                                                      [130, 143],
                                                      [140, 150]]},
                     'frame_gap': 1,
                     'cluster_cfg': {'config_a_2cam': [{'downsample_rate': 0.02},
                                                       {'downsample_rate': 0.2}]},
                     'volume_scalar': {'config_a_2cam': 512},
                     'aligned_scene': None,
                     'max_frame': 1003,
                     'start_frame': 0,
                     'eval_start_frame': -1,
                     'interact': False}},
 'test': {'type': 'EmbodiedDataset',
          'phase': 'all',
          'env_cfg': {'data_dir': '/data1/userdata/tcweng/projects/tcgs/datasets/deform360/derived/t17_scene_packages/pink_cloth_episode_0',
                      'scene_list': ['config_a_2cam'],
                      'sub_img_dir': 'color',
                      'sub_video_dir': 'color',
                      'cam_transform_fn': None,
                      'resolution': [360, 640],
                      'load_imgs': False,
                      'scale_x_angle': 1.0,
                      'max_cam_num': 2,
                      'max_cam_total': 2,
                      'max_seq': 15,
                      'pad_cam': False,
                      'llffhold': 0,
                      'tracking_pcd': 'track_process_data.pkl',
                      'prompt_dict': {'object': ['cloth'], 'obstacle': []},
                      'bounding_box': None,
                      'use_random_background': {'config_a_2cam': False},
                      'const_white_bg': {'config_a_2cam': False},
                      'controller_cfg': {'config_a_2cam': [{'num_cluster': 10},
                                                           {'downsample_rate': 0.5}]},
                      'cluster_type': 'dis_split',
                      'gravity': [0.0, 0.0, -9.8],
                      'rot_est': {'config_a_2cam': [0.0, 0.0, 0.0, 1.0]},
                      'dt': 0.03333333333333333,
                      'real_dt': {'config_a_2cam': 0.06666666666666667},
                      'split_list': {'config_a_2cam': [[0, 13],
                                                       [10, 23],
                                                       [20, 33],
                                                       [30, 43],
                                                       [40, 53],
                                                       [50, 63],
                                                       [60, 73],
                                                       [70, 83],
                                                       [80, 93],
                                                       [90, 103],
                                                       [100, 113],
                                                       [110, 123],
                                                       [120, 133],
                                                       [130, 143],
                                                       [140, 150]]},
                      'frame_gap': 1,
                      'cluster_cfg': {'config_a_2cam': [{'downsample_rate': 0.02},
                                                        {'downsample_rate': 0.2}]},
                      'volume_scalar': {'config_a_2cam': 512},
                      'aligned_scene': None,
                      'max_frame': 1003,
                      'start_frame': 0,
                      'eval_start_frame': -1,
                      'interact': False}}}

optimizer = {'type': 'Adam', 'lr': 0.0004, 'betas': (0.9, 0.999), 'weight_decay': 0, 'amsgrad': False}

optimizer_config = {'grad_clip': {'max_norm': 1.0}}

lr_config = {'by_epoch': True, 'policy': 'Hood', 'decay_rate': 0.5, 'decay_steps': 2, 'step_start': -1}

runner = {'type': 'EpochRunner', 'max_epochs': 61, 'max_iters': None}

checkpoint_config = {'by_epoch': True, 'interval': 1, 'max_keep_ckpts': 10000}

evaluation = {'by_epoch': True, 'interval': 1}

work_dir = '/data1/userdata/tcweng/projects/tcgs/outputs/deform360/stage2/config_a_seed5/'

load_from = '/data1/userdata/tcweng/projects/tcgs/outputs/deform360/stage1/config_a_seed5_normalizer_fix_resume_epoch2/epoch_46.pth'

resume_from = None
