#!/usr/bin/env python3
"""T24.5 non-gating coarse first-divergence trace. No training or algorithm changes.
Reference .pt files are comparison oracles only, never resume inputs.
All CUDA requires a Slurm allocation. No source patch or future PLY reset.
"""
import argparse, copy, hashlib, json, logging, os, subprocess, sys, time, traceback, types
from pathlib import Path
import numpy as np

def sha(p):
    return hashlib.sha256(Path(p).read_bytes()).hexdigest()

def main():
    ap=argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--workspace',type=Path,required=True)
    ap.add_argument('--output',type=Path,required=True)
    ap.add_argument('--label',choices=['A','B'],required=True)
    ap.add_argument('--checkpoint-dir',type=Path,required=True)
    args=ap.parse_args()
    assert os.environ.get('SLURM_JOB_ID'), 'CUDA requires Slurm'
    root=args.workspace.resolve(); repo=root/'SoMA'; os.chdir(repo); sys.path.insert(0,str(repo))
    cp=repo/'docs/deform360/contracts/008-pink-cloth/episode_0'
    args.output.mkdir(parents=True,exist_ok=True)
    report_path=args.output/(args.label+'_report.json')
    assert not report_path.exists(), 'No overwrite'
    report={'process':args.label,'status':'IN_PROGRESS','job_id':os.environ['SLURM_JOB_ID'],
            'pid':os.getpid(),'tool_sha256':sha(__file__), 'seed':5,
            'scope':'T24.5 coarse boundaries, fresh resumed instances/repeats only; no training',
            'targets':[123], 'head':subprocess.check_output(['git','rev-parse','HEAD'],text=True).strip()}
    started=time.monotonic()
    try:
        execute(args,root,repo,cp,report)
        report['status']='PASS'
    except Exception:
        report['status']='FAIL';report['exception']=traceback.format_exc()
        raise
    finally:
        report['wall_seconds']=time.monotonic()-started
        report_path.write_text(json.dumps(report,indent=2)+'\n')
        print('T24.5 coarse',args.label,report['status'],flush=True)

def execute(args,root,repo,cp,report):
    import torch
    from mmcv import Config
    from mmcv.runner import build_runner, build_optimizer
    from mmgs.datasets.embodied_dataset import EmbodiedDataset
    from mmgs.models.builder import build_simulator
    import mmgs.core.runner
    assert torch.cuda.is_available()
    report['gpu']=subprocess.check_output(['nvidia-smi','--query-gpu=name,memory.total','--format=csv,noheader'],text=True).strip()
    torch.manual_seed(5);np.random.seed(5);torch.set_num_threads(4)
    torch.backends.cudnn.benchmark=False
    torch.backends.cudnn.deterministic=True
    source_files=['mmgs/models/simulators/gs_simulator_embodied.py','mmgs/models/utils/dgl_graph.py',
        'mmgs/models/heads/acc_decoder.py','mmgs/datasets/embodied_dataset.py']
    report['source_sha256']={p:sha(repo/p) for p in source_files}
    sample_report=json.loads((cp/'dataset_sample_contract.json').read_text())
    env=sample_report['configurations']['A']['env_cfg']
    scene=Path(env['data_dir'])/env['scene_list'][0];name=scene.name
    immutable={str(p):sha(p) for p in scene.rglob('*') if p.is_file() and 'cluster_mask' not in p.parts and 'controller_mask' not in p.parts}
    # Directory links are not traversed by rglob: explicitly hash supervised images.
    for i in range(2):
        for frame in range(0,155,10):
            for p in [scene/'color'/str(i)/f'{frame}.png',scene/'mask'/str(i)/'1'/f'{frame}.png']:
                immutable[str(p)]=sha(p)
    np.random.seed(5);dataset=EmbodiedDataset(env_cfg=env,phase='train');sample=dataset[0]
    assert dataset.idx_mapping[0][2]==[0,1]
    assert sample['inputs']['gs_aligned_frame']==0 and sample['meta']['seq_num'].item()==10
    assert env['split_list'][name]==[[0,155]] and env['frame_gap']==10
    def batch(x):
        if isinstance(x,np.ndarray):return torch.from_numpy(x).unsqueeze(0).cuda()
        if isinstance(x,torch.Tensor):return x.unsqueeze(0).cuda()
        if isinstance(x,dict):return {k:batch(v) for k,v in x.items()}
        if isinstance(x,list):return [batch(v) for v in x]
        return x
    data=batch(sample);inputs=data['inputs'];gt=data['gt_label'];meta=data['meta']
    for cam in inputs['cam']:cam.to_device('cuda')
    # Official stage1 configuration previously generated by path-only relocation.
    cfgpath=root/'environment/soma-stage1-20260923/cloth_lift_stage1_external_data.py'
    cfg=Config.fromfile(str(cfgpath));mc=copy.deepcopy(cfg.model)
    mc['gs_scene']=[dict(name=name,model_path=str(scene/'pi3/gs/point_cloud/iteration_10000/point_cloud.ply'),sh_degree=0,num_seq=1,attr_name='rope')]
    mc['cluster_cfg']=env['cluster_cfg'];mc['controller_cfg']=env['controller_cfg']
    mc['train_cfg'].update(step_initial=1,max_rollout_step=1)
    report['model_config']=dict(mc);report['dataset_env_cfg']=env
    report['config_provenance']={'path':str(cfgpath),'sha256':sha(cfgpath),'basis':'Official cloth_lift stage1 with sample data paths relocated; scene/cluster/controller and rollout only overridden for this check.'}
    model=build_simulator(mc).cuda();model.init_weights();model.train()
    gaussian=model.gs_scene_dict[name];N=len(gaussian.get_xyz);assert N==12861
    gaussian_fields=['_xyz','_features_dc','_features_rest','_opacity','_scaling','_rotation']
    gaussian_before={k:getattr(gaussian,k).detach().clone() for k in gaussian_fields}
    registered={id(p) for p in model.parameters()}
    assert not any(id(getattr(gaussian,k)) in registered for k in gaussian_fields)
    traj=inputs['controller_trajectory'][0].float();assert tuple(traj.shape)==(16,30,3)
    expected=np.load(root/json.loads((cp/'controller_trajectory_contract.json').read_text())['output']['path_relative_to_workspace'],allow_pickle=False)[0:155:10]
    assert torch.equal(traj.cpu(),torch.from_numpy(expected))
    mapping=[[x[0].squeeze(0).long(),x[1].squeeze(0).long()] for x in inputs['p2c_mapping']]
    grouping=json.loads((cp/'controller_grouping_contract.json').read_text())
    for i,v in enumerate(grouping['p2c']):assert mapping[i][0].cpu().tolist()==v

    def cpu(x):
        if torch.is_tensor(x):return x.detach().cpu().clone()
        if isinstance(x,dict):return {k:cpu(v) for k,v in x.items()}
        if isinstance(x,list):return [cpu(v) for v in x]
        if isinstance(x,tuple):return tuple(cpu(v) for v in x)
        return copy.deepcopy(x)
    def exact(a,b,path='state'):
        if torch.is_tensor(a):
            assert torch.is_tensor(b) and a.shape==b.shape and a.dtype==b.dtype,path
            assert torch.isfinite(a).all() and torch.isfinite(b).all(),path
            assert torch.equal(a.cpu(),b.cpu()),path
        elif isinstance(a,dict):
            assert a.keys()==b.keys(),path+' keys'
            for k in a:exact(a[k],b[k],path+'/'+str(k))
        elif isinstance(a,(list,tuple)):
            assert type(a)==type(b) and len(a)==len(b),path
            for i,(x,y) in enumerate(zip(a,b)):exact(x,y,path+'/'+str(i))
        else:assert a==b,(path,a,b)
    def finite(x,path='value'):
        if torch.is_tensor(x):assert torch.isfinite(x).all(),path+' nonfinite'
        elif isinstance(x,dict):
            for k,v in x.items():finite(v,path+'/'+str(k))
        elif isinstance(x,(list,tuple)):
            for i,v in enumerate(x):finite(v,path+'/'+str(i))
    # Match T22 optimizer membership, including exclusion of nontrainable normalizer stats.
    optcfg=dict(cfg.optimizer);assert optcfg.pop('type')=='Adam'
    named={n:p for n,p in model.named_parameters() if p.requires_grad}
    optimizer=torch.optim.Adam(list(named.values()),**optcfg)
    report['optimizer_parameter_names']=list(named)
    assert not any(id(getattr(gaussian,k)) in {id(p) for g in optimizer.param_groups for p in g['params']} for k in gaussian_fields)
    def one_step():
        # Same real preprocessing/encode/decode/loss calls as T21/T22. No surrogate model.
        xyz=gaussian.get_xyz;cov=gaussian.get_covariance()
        attr=model.scene_attr[model._scene_attr_dict[name]].expand(N,-1)
        volume=torch.prod(gaussian.get_scaling*inputs['volume_scalar'].squeeze(0),dim=-1,keepdim=True)
        pin=torch.zeros((N+30,1),device='cuda');pin[:30]=1
        graphs,connections=model._preprocess(xyz.detach(),xyz,xyz,traj[0].detach(),traj[1].detach(),traj[0],
            attr,volume,cov,inputs['external'].squeeze(0),mapping,pin_mask=pin)
        labels=[v[0,1] for v in gt]
        out=model.encode_decode(graphs,connections,gaussian,inputs['cam'],
            cov.detach().clone(),xyz.detach().clone(),30,register_norm=True,
            gt_label=labels,rollout_size=1,cln_gaussian=gaussian,white_bg_list=inputs.get('white_bg'))
        finite(out,'encode_decode')
        losses=out[-1]
        losses.update(model._encode_decode_train(out[4],labels,
            [m[0,1] for m in inputs['controller_img_mask_list']],inputs['bbox'][0,:,1]))
        finite(losses,'loss')
        return losses,{'pred_pos':out[0],'pred_cov':out[1],'render':out[4]}
    runner=build_runner(dict(type='EpochRunner',max_epochs=1),default_args=dict(
        model=model,optimizer=optimizer,work_dir=str(args.output),logger=logging.getLogger('t24'),
        meta={'t24':'new finite rollout1 state','seed':5,'source_targets':[123]}))
    report['absent_runtime_attributes']=[k for k in ['global_step','iters_per_epoch'] if not hasattr(model,k)]
    checkpoint=args.checkpoint_dir/'epoch_1.pth'
    refpath=args.checkpoint_dir/'reference_state.pt'
    checkpoint_hash_before=sha(checkpoint)
    def runtime():
        return {k:getattr(model,k) for k in ['num_iter','num_epoch','global_step','iters_per_epoch','is_est_vel'] if hasattr(model,k)}
    def fixed_output():
        model.eval()
        before=cpu(model.state_dict());optbefore=cpu(optimizer.state_dict());rtbefore=runtime()
        with torch.no_grad():loss,output=one_step()
        exact(before,cpu(model.state_dict()),'eval_state_unchanged')
        exact(optbefore,cpu(optimizer.state_dict()),'eval_optimizer_unchanged')
        exact(rtbefore,runtime(),'eval_runtime_unchanged')
        finite([loss,output],'fixed_output')
        return cpu({'steps':[output],'loss':loss})
    import random
    from collections import defaultdict
    import functools
    def rng():
        return {'python':hashlib.sha256(repr(random.getstate()).encode()).hexdigest(),
                'numpy':hashlib.sha256(repr(np.random.get_state()).encode()).hexdigest(),
                'torch_cpu':sha_tensor(torch.get_rng_state()),'torch_cuda':sha_tensor(torch.cuda.get_rng_state())}
    def sha_tensor(t):return hashlib.sha256(t.detach().cpu().contiguous().numpy().tobytes()).hexdigest()
    trace=[];counts=defaultdict(int);values={};stats={}
    def record(site,obj):
        n=counts[site];counts[site]+=1;key=f'{len(trace):03d}:{site}:{n}';trace.append(key)
        def flatten(x,path):
            if torch.is_tensor(x):
                assert torch.isfinite(x).all(),path
                c=x.detach().cpu().clone();values[path]=c
                stats[path]={'shape':list(x.shape),'dtype':str(x.dtype),'device':str(x.device),
                  'stride':list(x.stride()),'contiguous':x.is_contiguous(),'finite':True,'sha256':sha_tensor(c),
                  'min':float(c.min()) if c.numel() else None,'max':float(c.max()) if c.numel() else None,
                  'mean':float(c.double().mean()) if c.numel() else None}
            elif hasattr(x,'ndata') and hasattr(x,'edges'):
                u,v=x.edges(order='eid');flatten(u,path+'/src');flatten(v,path+'/dst')
                for k in sorted(x.ndata.keys()):flatten(x.ndata[k],path+'/node/'+k)
                for k in sorted(x.edata.keys()):flatten(x.edata[k],path+'/edge/'+k)
            elif isinstance(x,dict):
                for k in sorted(x,key=str):flatten(x[k],path+'/'+str(k))
            elif isinstance(x,(list,tuple)):
                for i,v in enumerate(x):flatten(v,path+'/'+str(i))
        flatten(obj,key)
    handles=[];restores=[]
    def wrap(obj,name,site,select_input=None,select_output=None):
        original=getattr(obj,name)
        @functools.wraps(original)
        def observed(*a,**kw):
            record(site+'.input',select_input(a,kw) if select_input else (a,kw))
            result=original(*a,**kw)
            record(site+'.output',select_output(result) if select_output else result)
            return result
        setattr(obj,name,observed);restores.append((obj,name,original))
    def instrument():
        wrap(model,'_preprocess','preprocess')
        wrap(model.backbone,'forward','backbone',lambda a,k:a)
        wrap(model.backbone.encoder,'forward','encoder',lambda a,k:a)
        wrap(model.decode_head.dynamic_proj,'forward','dynamic_proj')
        wrap(model.decode_head,'pre_predict','decoder')
        wrap(model.decode_head,'pre_render','render',lambda a,k:{'pos':k['pos'],'cov':k['cov3D_precomp'],'opacity':k['opacity'],
             'rotation':k.get('rotation'),'features':k['scene_gaussian'].get_features})
        wrap(model,'encode_decode','simulator',lambda a,k:{'graphs':a[0],'connections':a[1]},
             lambda o:{'pred_pos':o[0],'pred_cov':o[1],'deformation':o[2],'images':o[4],'loss_regularization':o[-1]})
        wrap(model,'_encode_decode_train','image_loss')
    def uninstru():
        while restores:
            ob,n,orig=restores.pop();setattr(ob,n,orig)
    def run_trace(label):
        nonlocal trace,counts,values,stats
        trace=[];counts=defaultdict(int);values={};stats={}
        model.eval();before=cpu(model.state_dict());opt_before=cpu(optimizer.state_dict());rb=rng()
        with torch.no_grad():
            record('fixed_input',{'controller':traj,'gaussian':gaussian_before,'external':inputs['external'],
                 'mapping':mapping,'gt':gt,'camera':[{k:getattr(c,k) for k in ['world_view_transform','full_proj_transform','camera_center']} for c in inputs['cam']]})
            out=fixed_output();record('final',out)
        ra=rng();assert rb==ra,'RNG consumed during fixed forward'
        exact(before,cpu(model.state_dict()),'state_unchanged');exact(opt_before,cpu(optimizer.state_dict()),'opt_unchanged')
        path=args.output/(args.label+'_'+label+'_trace.pt');assert not path.exists()
        torch.save(values,path)
        summary={'label':label,'stages':trace,'stats':stats,'rng_before':rb,'rng_after':ra,'rng_consumed':False,
                 'trace_path':str(path),'trace_bytes':path.stat().st_size,'sha256':sha(path),
                 'model_hashes':{k:sha_tensor(v) for k,v in before.items()}}
        (args.output/(args.label+'_'+label+'_trace.json')).write_text(json.dumps(summary,indent=2)+'\n')
        report.setdefault('traces',[]).append({k:v for k,v in summary.items() if k not in ['stats','model_hashes']})
        values={};stats={}
    runner.resume(str(checkpoint),map_location='cpu')
    report['checkpoint_sha256']=sha(checkpoint);report['optimizer_steps']=0
    instrument();run_trace('M0_first');run_trace('M0_repeat');uninstru()
    m0=(model,optimizer,runner,gaussian,named)
    model=build_simulator(copy.deepcopy(mc)).cuda();model.init_weights()
    named={n:p for n,p in model.named_parameters() if p.requires_grad};optimizer=torch.optim.Adam(list(named.values()),**optcfg)
    runner=build_runner(dict(type='EpochRunner',max_epochs=1),default_args=dict(model=model,optimizer=optimizer,
        work_dir=str(args.output),logger=logging.getLogger('t245')))
    gaussian=model.gs_scene_dict[name];runner.resume(str(checkpoint),map_location='cpu')
    exact(cpu(m0[0].state_dict()),cpu(model.state_dict()),'same_checkpoint_models')
    instrument();run_trace('M1_first');uninstru()
    model,optimizer,runner,gaussian,named=m0
    instrument();run_trace('M0_after_M1');uninstru()
    for k,v in gaussian_before.items():exact(v,getattr(gaussian,k).detach(),k)
    for p,h in immutable.items():assert sha(p)==h,p
    for p,h in report['source_sha256'].items():assert sha(repo/p)==h,p
    assert sha(checkpoint)==checkpoint_hash_before
    report['input_checkpoint_source_unchanged']=True

if __name__=='__main__':main()
